### ISSUE TITLE
[Packaging] Ubuntu PyPy PPA breaks pip

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#2967]
In Heptapod by bitbucket_importer on Mar 1, 2019, 12:52

*Created originally on Bitbucket by [Fake Name (Connor Wolf)](https://bitbucket.org/[7.3.7](https://github.com/gitlab-importer/pypy/milestone/7)B5f219317-8906-434e-b9c0-bc487f11e457%7D/)*

Basically, I'm *attempting* to install pypy3 using what I believe is the (new!) official PPA (https://launchpad.net/~pypy/+archive/ubuntu/ppa).

Pypy installs fine,but I can't get pip to install properly for the life of me:

```
durr@rwpscrape ~> sudo apt-get install pypy3
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  pypy3-lib
Suggested packages:
  pypy3-doc pypy3-tk
The following NEW packages will be installed:
  pypy3 pypy3-lib
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 11.7 MB of archives.
After this operation, 77.4 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://ppa.launchpad.net/pypy/ppa/ubuntu bionic/main amd64 pypy3-lib amd64 7.0.0+dfsg-2~ppa1~ubuntu18.04 [2,333 kB]
Get:2 http://ppa.launchpad.net/pypy/ppa/ubuntu bionic/main amd64 pypy3 amd64 7.0.0+dfsg-2~ppa1~ubuntu18.04 [9,375 kB]
Fetched 11.7 MB in 21s (563 kB/s)
Selecting previously unselected package pypy3-lib:amd64.
(Reading database ... 109833 files and directories currently installed.)
Preparing to unpack .../pypy3-lib_7.0.0+dfsg-2~ppa1~ubuntu18.04_amd64.deb ...
Unpacking pypy3-lib:amd64 (7.0.0+dfsg-2~ppa1~ubuntu18.04) ...
Selecting previously unselected package pypy3.
Preparing to unpack .../pypy3_7.0.0+dfsg-2~ppa1~ubuntu18.04_amd64.deb ...
Unpacking pypy3 (7.0.0+dfsg-2~ppa1~ubuntu18.04) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Setting up pypy3-lib:amd64 (7.0.0+dfsg-2~ppa1~ubuntu18.04) ...
Setting up pypy3 (7.0.0+dfsg-2~ppa1~ubuntu18.04) ...
running pypy3 rtupdate hooks for 7.0
running pypy3 post-rtupdate hooks for 7.0
durr@rwpscrape ~> sudo pypy3 -m ensurepip
Traceback (most recent call last):
  File "/usr/lib/pypy3/lib-python/3/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/pypy3/lib-python/3/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/pypy3/lib-python/3/ensurepip/__main__.py", line 4, in <module>
    ensurepip._main()
  File "/usr/lib/pypy3/lib-python/3/ensurepip/__init__.py", line 221, in _main
    version="pip {}".format(version()),
  File "/usr/lib/pypy3/lib-python/3/ensurepip/__init__.py", line 79, in version
    assert len(wheel_names) == 1, wheel_names
AssertionError: []
durr@rwpscrape ~> sudo pypy3 get-pip.py
The directory '/home/durr/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/durr/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 10.4MB/s
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/d1/6a/4b2fcefd2ea0868810e92d519dacac1ddc64a2e53ba9e3422c3b62b378a6/setuptools-40.8.0-py2.py3-none-any.whl (575kB)
    100% |████████████████████████████████| 583kB 12.9MB/s
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/96/ba/a4702cbb6a3a485239fbe9525443446203f00771af9ac000fa3ef2788201/wheel-0.33.1-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
  The script wheel is installed in '/usr/lib/pypy3/../../local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-19.0.3 setuptools-40.8.0 wheel-0.33.1
durr@rwpscrape ~> pypy3 -m pip
/usr/bin/pypy3: No module named pip
durr@rwpscrape ~> pypy3 -m pip
/usr/bin/pypy3: No module named pip
durr@rwpscrape ~> pip
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 6, in <module>
    from pip._internal import main
ImportError: No module named 'pip'
durr@rwpscrape ~> pip3
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 6, in <module>
    from pip._internal import main
ImportError: No module named 'pip'
durr@rwpscrape ~>
```

So, `ensurepip` is broken, `get-pip.py` does *something*, but the `pip` module isn't present afterwards, and it breaks `pip3` (which was present from python3 already).

How are you supposed to install pip on the PPA pypy?

**Comment by mattip** [comment]
Closing as fixed
