### ISSUE TITLE
Multiprocessing leaking file descriptors

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3154]
In Heptapod by bitbucket_importer on Jan 16, 2020, 12:20

*Created originally on Bitbucket by [Callation (Andrew Robinson)](https://bitbucket.org/[7.3.7](https://github.com/gitlab-importer/pypy/milestone/7)Befc25329-dfb4-4bef-8d3e-4afa6c9780b5%7D/)*

Have migrated a multiprocessing project from PyPy 6.0 \(2.7\) to PyPy 7.3 \(3.6\) and have identified an issue with multiprocessing leaking descriptors. I believe this may also relate to the issue reported as #3060.

I have identified this issue as repeatable on both Ubuntu 18.04.2 and CentOS 7.0.

Simple code to reproduce issue \(Taken from #3111 which is raised a different issue, but current issue is reproduced with the same code sample\):

```
import multiprocessing

def process_chunk(chunk_index):
    return ([],[],[])

def main():
    i = 0
    with multiprocessing.Pool(5, maxtasksperchild=1) as p:
        for sub_headers, sub_results, sub_scores in p.imap_unordered(process_chunk, range(5000)):
            print(i)
            i += 1

if __name__ == '__main__':
    main()
```

If saving the above as “test.py” the descriptor leak can be verified by running “/path/to/pypy3 test.py” then taking the PID from ps and doing an “ls -l /proc/PID/fd” and comparing to the same when running native Python Ie. Running “/path/to/python3 test.py” taking PID and “ls -l /proc/PID/fd”.

Under native Python3 the descriptor list remains constant at 9 pipe entries.

Under PyPy the file descriptor list keeps growing until ulimit is reached and it will throw an exception as “OSError: \[Errno 24\] Too many open files“. In my case ulimit is set to 1024.

Traceback below:

‌

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/callation/pypy3/lib-python/3/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/callation/pypy3/lib-python/3/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/callation/pypy3/lib-python/3/multiprocessing/pool.py", line 405, in _handle_workers
    pool._maintain_pool()
  File "/opt/callation/pypy3/lib-python/3/multiprocessing/pool.py", line 246, in _maintain_pool
    self._repopulate_pool()
  File "/opt/callation/pypy3/lib-python/3/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/opt/callation/pypy3/lib-python/3/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/opt/callation/pypy3/lib-python/3/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/opt/callation/pypy3/lib-python/3/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/callation/pypy3/lib-python/3/multiprocessing/popen_fork.py", line 65, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files
```

‌

**Comment by muraj238** [comment]
Still present in the latest pypy 3.10

**Comment by mattip** [comment]
Are you sure this happens on the recently released v7.3.16? I could not reproduce the leak on that version on macos-arm64. I did find a leak and fixed it in 79502e4b7 which was part of that release. For good measure, I just now added a0878f5f7 which should fix a semaphore leak as well.

**Comment by mattip** [comment]
It seems a0878f5f7 was already part of py3.10...

**Comment by devdanzin** [comment]
I was able to reproduce the issue by setting start method to spawn on WSL, then running the repro code. Is it expected to fail with too many open files with that method?

**Comment by muraj238** [comment]
I use the 7.3.16 as well. The problem happened when I used multiprocessing Manager to create a Namespace and one item in the namespace was a list created with the manager as well. When I moved the list outside the namespace, the problem seems no longer present. I added del statements on both ends just to be sure, but it seems to work without them as well. I create one namespace for each request of a web application, maybe, with two manager objects one inside another, they weren't properly garbage collected or something? I'll keep watching it, hopefully the problem won't show itself again.

**Comment by devdanzin** [comment]
> The problem happened when I used multiprocessing Manager to create a Namespace and one item in the namespace was a list created with the manager as well.

Can you share that version of your code?

**Comment by muraj238** [comment]
> > The problem happened when I used multiprocessing Manager to create a Namespace and one item in the namespace was a list created with the manager as well.
> 
> Can you share that version of your code?

Not sure what you mean, it's a complex app, but the way it was defined is this. I probably should have mentioned that I'm using aioprocessing, not multiprocessing directly.

```
self.manager = aioprocessing.AioManager()

.
.
.

request = self.manager.Namespace(
        id=request_id,
        username=user.username,
        ownership=ownership,
        permissions=user.permissions,
        selected_objects=selected_objects,
        result=self.manager.list(),
)
```

When I changed it this way, the problem disappeared:

```
request = self.manager.Namespace(
        id=request_id,
        username=user.username,
        ownership=ownership,
        permissions=user.permissions,
        selected_objects=selected_objects,
)
result = self.manager.list()
```

After creating these objects, I'm putting them into self.manager.AioQueue() instance and then waiting till child process fills the result:


```
while True:
    try:
        result = result_list[0]
    except IndexError:
        await asyncio.sleep(0)
        continue

    if isinstance(result, BaseException):
        raise result
    else:
        return result
```

**Comment by devdanzin** [comment]
Maybe related: https://github.com/python/cpython/issues/118981

**Comment by mattip** [comment]
I don't think that cpython issue is related. That is for an error path in forking, I don't see where the test script at the top of the issue (the one from #3111) will error, and on linux does not use forking.

The script does not run to completion for me on cpython 3.10, 3.11, 3.12. It occasionally gets to 1000 before hanging, but sometimes hangs as early as 400 iterations. @muraj238 could you turn your pieces of code into something I can run?

**Comment by steve-anunknown** [comment]
I'm facing the same problem trying to parallelize a script of mine and I managed to come up with a minimal program that reproduces the problem:

```python
import multiprocessing as mp
import numpy as np

def kernel(inlist, index):
    return (index, sum(inlist))

def do_computation():
    tasks = [(list(range(5000)), index) for index in range(Z)]
    with mp.Pool() as pool:
        results = pool.starmap(kernel, tasks)

    return results

def main():
    array = np.zeros((X,Y,Z))
    for i in range(X):
        for j in range(Y):
            results = do_computation()
            for k, s in results:
                array[i, j, k] = s
    print(array)

if __name__ == '__main__':
    X = 15
    Y = 30
    Z = 4
    main()
```

This program will terminate with `OSError [Errno 24]` when run with `PyPy 7.3.17 Python 3.10.14` but will terminate successfully when run with `cpython Python 3.10.12` (these happen to be the versions in my machine). I hope this helps a bit in untangling the problem.

**Comment by mattip** [comment]
I added another resource `close()` in 8d143fd which is part of py3.11. The same fix was not enough to fix the program on py3.10. The code is pure python, so feel free to dig around and try to figure out what resources are leaking and where more `close()` calls are missing.

**Comment by mattip** [comment]
Hmm. That was the wrong fix, it broke tests. Reverting.

**Comment by steve-anunknown** [comment]
I'm not really familiar with the inner workings of pypy but I have noticed that, in the snippet that I provided above to reproduce the problem, if the garbage collector is called after the pool work finishes, the error is not triggered:
```python
import multiprocessing as mp
import numpy as np
import gc # <------ I added this line here

def kernel(inlist, index):
    return (index, sum(inlist))

def do_computation():
    tasks = [(list(range(5000)), index) for index in range(Z)]
    with mp.Pool() as pool:
        results = pool.starmap(kernel, tasks)
    gc.collect() # <---- I added this line here
    return results

def main():
    array = np.zeros((X,Y,Z))
    for i in range(X):
        for j in range(Y):
            results = do_computation()
            for k, s in results:
                array[i, j, k] = s
    print(array)

if __name__ == '__main__':
    X = 15
    Y = 30
    Z = 4
    main()
  ```
  
  Is this behaviour expected?

**Comment by mattip** [comment]
No, I don't know why it is happenning. It seems putting a `gc.collect` anywhere in the code "solves" the resource leak. Typically this is because somewhere someone is not calling `close()` to release the handles created in `os.pipe()`. `gc.collect` is a big hammer to solve this problem since collecting the objects releases the resources. But that is not the correct solution, since it relies on the garbage collector to run. The problem is finding the correct place to `close()` without breaking other code paths.

**Comment by steve-anunknown** [comment]
Ok, I understand. I compared the code of multiprocessing lib in cpython and pypy and I see no differences. Therefore, I believe that the bug should also be reproducible in cpython, but under different circumstances.

Searching a bit in the cpython open issues, I noticed this one that looks relevant: https://github.com/python/cpython/issues/124706. They seem to have made the same observation regarding the garbage collector. A comment there suggests that the garbage collector is not able to close the files fast enough.

To my understanding, this hints that the implementation implicitly relies on the garbage collector to close the resources. If that is the case, then either the resources must be forcefully closed or the garbage collector must be tweaked to handle them appropriately.
