### ISSUE TITLE
readline module raises InvalidTerminal with TERM=dumb - test failures and cpython differences

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3308]
In Heptapod by @stefanor on Sep 24, 2020, 08:00

In some build environments, I historically had some readline tests lock up on some architectures, so I build with `TERM=dumb`. This triggers some bugs:

## REPL in 3.6:

`site.py` initializes readline, causing a trackback to the terminal on REPL start-up:

```
$ TERM=dumb pypy3
Python 3.6.9 (7.3.2~rc2+dfsg-1, Sep 23 2020, 01:53:42)
[PyPy 7.3.2 with GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "/usr/lib/pypy3/lib-python/3/site.py", line 437, in register_readline
    if readline.get_current_history_length() == 0:
  File "/usr/lib/pypy3/lib_pypy/pyrepl/readline.py", line 309, in get_current_history_length
    return len(self.get_reader().history)
  File "/usr/lib/pypy3/lib_pypy/pyrepl/readline.py", line 251, in get_reader
    console = UnixConsole(self.f_in, self.f_out, encoding=ENCODING)
  File "/usr/lib/pypy3/lib_pypy/pyrepl/unix_console.py", line 116, in __init__
    self._clear = _my_getstr("clear")
  File "/usr/lib/pypy3/lib_pypy/pyrepl/unix_console.py", line 57, in _my_getstr
    "terminal doesn't have the required '%s' capability"%cap)
pyrepl.unix_console.InvalidTerminal: terminal doesn't have the required 'clear' capability
>>>> 
```

cpython seems to just handle the situation (and readline functions).

## Readline tests:

On 3.6:

```
======================================================================
ERROR: testHistoryUpdates (test.test_readline.TestHistoryManipulation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/lib-python/3/test/test_readline.py", line 32, in testHistoryUpdates
    readline.clear_history()
  File "/<<PKGBUILDDIR>>/lib_pypy/pyrepl/readline.py", line 346, in clear_history
    del self.get_reader().history[:]
  File "/<<PKGBUILDDIR>>/lib_pypy/pyrepl/readline.py", line 251, in get_reader
    console = UnixConsole(self.f_in, self.f_out, encoding=ENCODING)
  File "/<<PKGBUILDDIR>>/lib_pypy/pyrepl/unix_console.py", line 116, in __init__
    self._clear = _my_getstr("clear")
  File "/<<PKGBUILDDIR>>/lib_pypy/pyrepl/unix_console.py", line 57, in _my_getstr
    "terminal doesn't have the required '%s' capability"%cap)
pyrepl.unix_console.InvalidTerminal: terminal doesn't have the required 'clear' capability

======================================================================
ERROR: test_nonascii_history (test.test_readline.TestHistoryManipulation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/lib-python/3/test/test_readline.py", line 94, in test_nonascii_history
    readline.clear_history()
  File "/<<PKGBUILDDIR>>/lib_pypy/pyrepl/readline.py", line 346, in clear_history
    del self.get_reader().history[:]
  File "/<<PKGBUILDDIR>>/lib_pypy/pyrepl/readline.py", line 251, in get_reader
    console = UnixConsole(self.f_in, self.f_out, encoding=ENCODING)
  File "/<<PKGBUILDDIR>>/lib_pypy/pyrepl/unix_console.py", line 116, in __init__
    self._clear = _my_getstr("clear")
  File "/<<PKGBUILDDIR>>/lib_pypy/pyrepl/unix_console.py", line 57, in _my_getstr
    "terminal doesn't have the required '%s' capability"%cap)
pyrepl.unix_console.InvalidTerminal: terminal doesn't have the required 'clear' capability
```

(2.7 has the same issue, but the second test doesn't exist there)

That's a different behaviour to cPython, but doesn't seem worrying. Using readline without a terminal that supports it wouldn't make much sense. So, I'm just just ignoring it with this patch:

```diff
diff --git a/lib-python/3/test/test_readline.py b/lib-python/3/test/test_readline.py
index 17157a16..341fe9f8 100644
--- a/lib-python/3/test/test_readline.py
+++ b/lib-python/3/test/test_readline.py
@@ -10,6 +10,7 @@ import subprocess
 import sys
 import tempfile
 import unittest
+from pyrepl.unix_console import InvalidTerminal
 from test.support import import_module, unlink, temp_dir, TESTFN
 from test.support.script_helper import assert_python_ok
 
@@ -29,7 +30,10 @@ class TestHistoryManipulation (unittest.TestCase):
     """
 
     def testHistoryUpdates(self):
-        readline.clear_history()
+        try:
+            readline.clear_history()
+        except InvalidTerminal as e:
+            raise unittest.SkipTest(e)
 
         readline.add_history("first line")
         readline.add_history("second line")
@@ -91,7 +95,10 @@ class TestHistoryManipulation (unittest.TestCase):
         readline.write_history_file(hfilename)
 
     def test_nonascii_history(self):
-        readline.clear_history()
+        try:
+            readline.clear_history()
+        except InvalidTerminal as e:
+            raise unittest.SkipTest(e)
         try:
             readline.add_history("entrée 1")
         except UnicodeEncodeError as err:
```

## 3.6 rlcompleter module test failures

From the description of the rlcompleter module, it should be useful when readline isn't available, but again, it blows up with `TERM=dumb`.

```
======================================================================
ERROR: test_attr_matches (test.test_rlcompleter.TestRlcompleter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/lib-python/3/test/test_rlcompleter.py", line 20, in setUp
    self.stdcompleter.complete('', 0)
  File "/<<PKGBUILDDIR>>/lib-python/3/rlcompleter.py", line 79, in complete
    readline.insert_text('\t')
  File "/<<PKGBUILDDIR>>/lib_pypy/pyrepl/readline.py", line 396, in insert_text
    return self.get_reader().insert(text)
  File "/<<PKGBUILDDIR>>/lib_pypy/pyrepl/readline.py", line 251, in get_reader
    console = UnixConsole(self.f_in, self.f_out, encoding=ENCODING)
  File "/<<PKGBUILDDIR>>/lib_pypy/pyrepl/unix_console.py", line 116, in __init__
    self._clear = _my_getstr("clear")
  File "/<<PKGBUILDDIR>>/lib_pypy/pyrepl/unix_console.py", line 57, in _my_getstr
    "terminal doesn't have the required '%s' capability"%cap)
pyrepl.unix_console.InvalidTerminal: terminal doesn't have the required 'clear' capability

...
FAILED (errors=7)
test_rlcompleter failed
```

Solveable with a simple (but ugly) patch:

```diff
--- a/lib-python/3/rlcompleter.py
+++ b/lib-python/3/rlcompleter.py
@@ -32,6 +32,7 @@ Notes:
 import atexit
 import builtins
 import __main__
+from pyrepl.unix_console import InvalidTerminal
 
 __all__ = ["Completer"]
 
@@ -76,11 +77,13 @@ class Completer:
         if not text.strip():
             if state == 0:
                 if _readline_available:
-                    readline.insert_text('\t')
-                    readline.redisplay()
-                    return ''
-                else:
-                    return '\t'
+                    try:
+                        readline.insert_text('\t')
+                        readline.redisplay()
+                        return ''
+                    except InvalidTerminal:
+                        pass
+                return '\t'
             else:
                 return None
```

## Conclusions

These are all essentially the same bug, which is that the pypy readline module doesn't match cpython's behaviour, and throws this `InvalidTerminal` exception, where cPython manages to avoid blowing up. Maybe because it isn't checking a return code or something? I haven't dived to the bottom of it, yet.

**Comment by mattip** [comment]
Running the example `TERM=dumb pypy/goal/pypy3.10-c` works fine for me. Closing, please open a new issue for other pyrepl problems.

**Comment by stefanor** [comment]
Thanks, but I think that dealt with it in the REPL while leaving the underlying issue in readline unresolved:

for example:
```
$TERM=dumb pypy3 -c "import rlcompleter; rlcompleter.Completer().complete('', 0)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/pypy3.10/rlcompleter.py", line 81, in complete
    readline.insert_text('\t')
  File "/usr/lib/pypy3.10/pyrepl/readline.py", line 500, in insert_text
    self.get_reader().insert(text)
    ^^^^^^^^^^^^^^^^^
  File "/usr/lib/pypy3.10/pyrepl/readline.py", line 357, in get_reader
    console = Console(self.f_in, self.f_out, encoding=ENCODING)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/pypy3.10/pyrepl/unix_console.py", line 173, in __init__
    self._clear = _my_getstr("clear")
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/pypy3.10/pyrepl/unix_console.py", line 166, in _my_getstr
    raise InvalidTerminal(
pyrepl.unix_console.InvalidTerminal: terminal doesn't have the required clear capability
```

vs
```
$ TERM=dumb python3 -c "import rlcompleter; rlcompleter.Completer().complete('', 0)"
$
```

That's because readline's behaviour is different:

```
$ TERM=dumb python3 -c "import readline; readline.get_line_buffer()"
$ TERM=dumb python3 -c "import readline; readline.insert_text('')"
```

```
$ TERM=dumb pypy3 -c "import readline; readline.get_line_buffer()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/pypy3.10/pyrepl/readline.py", line 482, in get_line_buffer
    return self.get_reader().get_unicode()
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/pypy3.10/pyrepl/readline.py", line 357, in get_reader
    console = Console(self.f_in, self.f_out, encoding=ENCODING)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/pypy3.10/pyrepl/unix_console.py", line 173, in __init__
    self._clear = _my_getstr("clear")
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/pypy3.10/pyrepl/unix_console.py", line 166, in _my_getstr
    raise InvalidTerminal(
pyrepl.unix_console.InvalidTerminal: terminal doesn't have the required clear capability
$ TERM=dumb pypy3 -c "import readline; readline.insert_text('')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/pypy3.10/pyrepl/readline.py", line 500, in insert_text
    self.get_reader().insert(text)
    ^^^^^^^^^^^^^^^^^
  File "/usr/lib/pypy3.10/pyrepl/readline.py", line 357, in get_reader
    console = Console(self.f_in, self.f_out, encoding=ENCODING)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/pypy3.10/pyrepl/unix_console.py", line 173, in __init__
    self._clear = _my_getstr("clear")
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/pypy3.10/pyrepl/unix_console.py", line 166, in _my_getstr
    raise InvalidTerminal(
pyrepl.unix_console.InvalidTerminal: terminal doesn't have the required clear capability
```

Of course that's visible in Python 3.13's pyrepl too. So we could deal with this bug in cPython. And until that's fixed, pypy's readline module will raise exceptions where cPython's doesn't.

```
$ TERM=dumb python3.13 -c "from _pyrepl.readline import _get_reader; _get_reader()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from _pyrepl.readline import _get_reader; _get_reader()
                                              ~~~~~~~~~~~^^
  File "/usr/lib/python3.13/_pyrepl/readline.py", line 358, in get_reader
    console = Console(self.f_in, self.f_out, encoding=ENCODING)
  File "/usr/lib/python3.13/_pyrepl/unix_console.py", line 173, in __init__
    self._clear = _my_getstr("clear")
                  ~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/_pyrepl/unix_console.py", line 166, in _my_getstr
    raise InvalidTerminal(
        f"terminal doesn't have the required {cap} capability"
    )
_pyrepl.unix_console.InvalidTerminal: terminal doesn't have the required clear capability
```

**Comment by mattip** [comment]
Reopening.
