### ISSUE TITLE
pypy3.8 system install: venv.create() fails on trying to copy stuff from /usr/lib

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3611]
In Heptapod by @mgorny on Dec 8, 2021, 21:34

It seems that while we've made the CLI work, the `venv.create()` function is doing some bad stuff:

```
$ pypy3 -c 'import venv; venv.create("/tmp/test")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/pypy3.8/venv/__init__.py", line 428, in create
    builder.create(env_dir)
  File "/usr/lib/pypy3.8/venv/__init__.py", line 67, in create
    self.setup_python(context)
  File "/usr/lib/pypy3.8/venv/__init__.py", line 277, in setup_python
    copier(src, dst)
  File "/usr/lib/pypy3.8/venv/__init__.py", line 179, in symlink_or_copy
    shutil.copytree(src, dst)
  File "/usr/lib/pypy3.8/shutil.py", line 560, in copytree
    dirs_exist_ok=dirs_exist_ok)
  File "/usr/lib/pypy3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/usr/bin/../lib/mgetty+sendfax/faxq-helper', '/tmp/test/lib/mgetty+sendfax/faxq-helper', "[Errno 13] Permission denied: '/usr/bin/../lib/mgetty+sendfax/faxq-helper'")]
```

I think this fails because the executable is not readable to the current user:
```
$ ls -lh /usr/bin/../lib/mgetty+sendfax/faxq-helper
-rws--x--x 1 fax root 31K 2021-03-02  /usr/bin/../lib/mgetty+sendfax/faxq-helper
```

```
$ pypy3 --version
Python 3.8.12 (9ef55f6fc3697bf8d85334ce2d70fdbba888e3ab, Oct 25 2021, 18:31:21)
[PyPy 7.3.7 with GCC 11.2.0]
```

**Comment by mattip** [comment]
Closing as fixed, please reopen or open a new issue if there are still failing edge cases.
