### ISSUE TITLE
Link failure with LLD

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3703]
In Heptapod by @xbjfk on Mar 13, 2022, 12:15

When generating `_curses_cffi.o` the following error arises:
```
ld.lld: error: /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../lib64/crti.o is incompatible with elf32-i386
ld.lld: error: /usr/lib/llvm/13/bin/../../../../lib/clang/13.0.1/lib/linux/clang_rt.crtbegin-x86_64.o is incompatible with elf32-i386
ld.lld: error: ./_curses_cffi.o is incompatible with elf32-i386
ld.lld: error: /usr/lib/llvm/13/bin/../../../../lib/clang/13.0.1/lib/linux/clang_rt.crtend-x86_64.o is incompatible with elf32-i386
ld.lld: error: /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../lib64/crtn.o is incompatible with elf32-i386
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pypy3-7.3.8/work/pypy3.9-v7.3.8-src/lib-python/3/distutils/unixccompiler.py", line 204, in link
    self.spawn(linker + ld_args)
  File "/var/tmp/portage/dev-python/pypy3-7.3.8/work/pypy3.9-v7.3.8-src/lib-python/3/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/var/tmp/portage/dev-python/pypy3-7.3.8/work/pypy3.9-v7.3.8-src/lib-python/3/distutils/spawn.py", line 91, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/usr/lib/llvm/13/bin/clang-13' failed with exit code 1
```

I suspect that this is because `-L/lib -L/usr/lib` are somehow added to the search path, and this causes the emulation to be set to elf32-i386 because of a linker script line in `OUTPUT_FORMAT(elf32-i386)` in some files. Removing the inclusion of `/lib` and `/usr/lib` manually fixes the issue, however I am not familiar enough with PyPy's build system to fix it there

See also:    
https://github.com/PhotoFlare/photoflare/pull/248/files    
https://www.mail-archive.com/llvm-bugs@lists.llvm.org/msg35333.html    
https://bugs.gentoo.org/show_bug.cgi?id=743700    

Clang + LLD work flawlessly on a non-multilib system.

Thanks.

**Comment by mattip** [comment]
> Later I will test this code on FreeBSD and OpenBSD and fix if needed.

Did you get a chance to check this?

**Comment by mattip** [comment]
@xbjfk: is the patch still needed?
