### ISSUE TITLE
Debugger Crash with PyPy 7.3.7: InvalidVirtualRef Error on Setting Breakpoints and Stepping Through Code

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3976]
In Heptapod by @xpinked on Aug 6, 2023, 09:51

After updating to the latest version of VSCode, 

My team and I have been experiencing debugging issues with our project when executed using PyPy. 

While we can initially attach the debugger, it crashes whenever we attempt to set breakpoints or step through the code, displaying a traceback error.

I've discussed this concern in the IRC chat on the following dates:

- https://libera.irclog.whitequark.org/pypy/2023-08-04
- https://libera.irclog.whitequark.org/pypy/2023-08-05
- https://libera.irclog.whitequark.org/pypy/2023-08-06

It's important to note that we're not planning to upgrade our PyPy version anytime soon. 

Our extensive project has numerous dependencies, and making such a change at our company's current stage would entail significant effort. 

We hope to find a solution that works within our constraints.
____________________________________

My Individual Environment 
````bash
OS: Windows 11, running WSL -  Ubuntu 22.04.1 LTS
````

Version:
````bash
Python 3.7.12 (44db26267d0a, Oct 24 2021, 14:21:50)
[PyPy 7.3.7 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
````

Traceback:
````bash
RPython traceback:
  File "pypy_interpreter.c", line 46977, in BuiltinCode3_fastcall_3
  File "pypy_interpreter_2.c", line 64234, in GetSetProperty_descr_property_get
  File "implement_3.c", line 22686, in descr_typecheck_fget_f_back
  File "rpython_jit_metainterp.c", line 1531, in force_virtual
Traceback (most recent call last):
  File "/home/my-pc/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 252, in _on_run
    self.process_net_command_json(self.py_db, json_contents)
  File "/home/my-pc/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 193, in process_net_command_json
    cmd = on_request(py_db, request)
  File "/home/my-pc/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 806, in on_setbreakpoints_request
    suspend_policy, hit_condition, is_logpoint, adjust_line=True, on_changed_breakpoint_state=on_changed_breakpoint_state)
  File "/home/my-pc/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_api.py", line 568, in add_breakpoint
    py_db.on_breakpoints_changed()
  File "/home/my-pc/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 1126, in on_breakpoints_changed
    self.set_tracing_for_untraced_contexts()
  File "/home/my-pc/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 1157, in set_tracing_for_untraced_contexts
    self.set_trace_for_frame_and_parents(frame)
  File "/home/my-pc/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2250, in set_trace_for_frame_and_parents
    frame = frame.f_back
SystemError: unexpected internal exception (please report a bug): <InvalidVirtualRef object at 0x7ff7d81209e8>; internal traceback was dumped to stderr
````

**Comment by mattip** [comment]
You might want to try to use debugd instead of debugpy. At least according to [this comment](https://github.com/microsoft/debugpy/issues/604#issuecomment-849631448) it might work?

**Comment by mattip** [comment]
cc @xpinked. Is this still relevant for your work?

**Comment by xpinked** [comment]
> cc @xpinked. Is this still relevant for your work?

In production we are still running with pypy3.7, but we are migrating now to regular python 3.11 (big jump).

So the majority of the developers are now using python 3.11, making the issue less relevant to us.

Although the bug itself still exists, to resolve it we debugged the code using pycharm instead of vscode.

**Comment by mattip** [comment]
I wonder what debugger pycharm uses under the hood by default.

If PyPy had a 3.11 offering, would that be attractive to you?

**Comment by xpinked** [comment]
> I wonder what debugger pycharm uses under the hood by default.
> 
> If PyPy had a 3.11 offering, would that be attractive to you?

Yes we are interested
