### ISSUE TITLE
"Fatal RPython error: AssertionError" in brotli

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#3999]
In Heptapod by @mgorny on Sep 12, 2023, 10:20

Reproduced with 7.3.12 and nightly.

```
test__test_compress_file_quality_11_lgwin_10_10x10y (tests.bro_test.TestBroCompress) ... RPython traceback:
  File "pypy_module_cpyext_1.c", line 6728, in wrapper_second_level__star_2_51
  File "implement.c", line 30134, in dispatcher_Py_21
Fatal RPython error: AssertionError
ERROR

======================================================================
ERROR: test__test_compress_file_quality_11_lgwin_10_10x10y (tests.bro_test.TestBroCompress)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/brotli/python/tests/_test_utils.py", line 66, in <lambda>
    return lambda self: method(self, *args, **kwargs)
  File "/tmp/brotli/python/tests/bro_test.py", line 90, in _test_compress_file
    self._compress_file(test_data, **kwargs)
  File "/tmp/brotli/python/tests/bro_test.py", line 75, in _compress_file
    subprocess.check_call(args, env=TEST_ENV)
  File "/tmp/pypy-c-jit-107713-1775742c19f7-linux64/lib/pypy3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/brotli/.venv/bin/python', '/tmp/brotli/python/bro.py', '-f', '-q', '11', '--lgwin', '10', '-i', '/tmp/brotli/tests/testdata/10x10y', '-o', '/tmp/tmptypw9b94/10x10y.bro']' died with <Signals.SIGABRT: 6>.

----------------------------------------------------------------------
Ran 1 test in 0.473s

FAILED (errors=1)
```

gdb:

```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f5b1a689e2f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f5b1a639cc2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f5b1a6224ed in __GI_abort () at abort.c:79
#4  0x00007f5b1cc5eab1 in pypy_debug_catch_fatal_exception () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#5  0x00007f5b1c191b1a in pypy_g_wrapper_second_level.star_2_51 ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#6  0x00007f5b18b7d6a6 in BlocksOutputBuffer_Finish (buffer=0x7ffddc93c390, avail_out=32768) at python/_brotli.c:186
#7  0x00007f5b18b7dbce in compress_stream (enc=0x17eafc0, op=BROTLI_OPERATION_PROCESS, input=0x1792bbc "XXXXXXXXXXYYYYYYYYYY", 
    input_length=20) at python/_brotli.c:320
#8  0x00007f5b18b7dea9 in brotli_Compressor_process (self=0x17ccfc0, args=0x17dfc50) at python/_brotli.c:447
#9  0x00007f5b1c281f71 in pypy_g_generic_cpy_call__StdObjSpaceConst_funcPtr_SomeI_13 ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#10 0x00007f5b1c28266d in pypy_g_W_PyCFunctionObject_call_varargs ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#11 0x00007f5b1b9f8d1d in pypy_g.call_4 () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#12 0x00007f5b1bbe4244 in pypy_g_BuiltinCodePassThroughArguments1_funcrun_obj ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#13 0x00007f5b1b96e4ad in pypy_g_dispatcher_funcrun_obj () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#14 0x00007f5b1bc7b7e5 in pypy_g_call_valuestack__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#15 0x00007f5b1c5af40d in pypy_g_CALL_METHOD__AccessDirect_star_1 ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#16 0x00007f5b1bc806ed in pypy_g_dispatch_bytecode__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#17 0x00007f5b1bc48872 in pypy_g_handle_bytecode__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#18 0x00007f5b1c37f3d0 in pypy_g_portal_11 () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#19 0x00007f5b1c7629eb in pypy_g_ll_portal_runner__Unsigned_Bool_pypy_interpreter ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#20 0x00007f5b1bc0b86a in pypy_g_execute_frame () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#21 0x00007f5b1cb4bb26 in __vmprof_eval_vmprof () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#22 0x00007f5b1c5af31b in pypy_g_CALL_METHOD_KW__AccessDirect_star_1 ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#23 0x00007f5b1bc7fffd in pypy_g_dispatch_bytecode__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#24 0x00007f5b1bc48872 in pypy_g_handle_bytecode__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#25 0x00007f5b1c37f3d0 in pypy_g_portal_11 () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#26 0x00007f5b1c7629eb in pypy_g_ll_portal_runner__Unsigned_Bool_pypy_interpreter ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#27 0x00007f5b1bc0b86a in pypy_g_execute_frame () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#28 0x00007f5b1cb4bb26 in __vmprof_eval_vmprof () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#29 0x00007f5b1bc7ca7f in pypy_g_CALL_FUNCTION__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#30 0x00007f5b1bc8086f in pypy_g_dispatch_bytecode__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#31 0x00007f5b1bc48872 in pypy_g_handle_bytecode__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#32 0x00007f5b1c37f3d0 in pypy_g_portal_11 () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#33 0x00007f5b1c7629eb in pypy_g_ll_portal_runner__Unsigned_Bool_pypy_interpreter ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#34 0x00007f5b1bc0b86a in pypy_g_execute_frame () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#35 0x00007f5b1cb4bb26 in __vmprof_eval_vmprof () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#36 0x00007f5b1be56474 in pypy_g_exec_ () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#37 0x00007f5b1b9970da in pypy_g_BuiltinActivation_UwS_ObjSpace_W_Root_W_Root_W_R_2 ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#38 0x00007f5b1bbe3f3b in pypy_g_BuiltinCode_funcrun_obj () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#39 0x00007f5b1bc7ca7f in pypy_g_CALL_FUNCTION__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#40 0x00007f5b1bc8086f in pypy_g_dispatch_bytecode__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#41 0x00007f5b1bc48872 in pypy_g_handle_bytecode__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#42 0x00007f5b1c37f3d0 in pypy_g_portal_11 () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#43 0x00007f5b1c7629eb in pypy_g_ll_portal_runner__Unsigned_Bool_pypy_interpreter ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#44 0x00007f5b1bc0b86a in pypy_g_execute_frame () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#45 0x00007f5b1cb4bb26 in __vmprof_eval_vmprof () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#46 0x00007f5b1bc7bcfd in pypy_g_CALL_FUNCTION_EX__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#47 0x00007f5b1bc80c8d in pypy_g_dispatch_bytecode__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#48 0x00007f5b1bc48872 in pypy_g_handle_bytecode__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#49 0x00007f5b1c37f3d0 in pypy_g_portal_11 () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#50 0x00007f5b1c7629eb in pypy_g_ll_portal_runner__Unsigned_Bool_pypy_interpreter ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#51 0x00007f5b1bc0b86a in pypy_g_execute_frame () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#52 0x00007f5b1cb4bb26 in __vmprof_eval_vmprof () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#53 0x00007f5b1bc7bcfd in pypy_g_CALL_FUNCTION_EX__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#54 0x00007f5b1bc80c8d in pypy_g_dispatch_bytecode__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#55 0x00007f5b1bc48872 in pypy_g_handle_bytecode__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#56 0x00007f5b1c37f3d0 in pypy_g_portal_11 () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#57 0x00007f5b1c7629eb in pypy_g_ll_portal_runner__Unsigned_Bool_pypy_interpreter ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#58 0x00007f5b1bc0b86a in pypy_g_execute_frame () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#59 0x00007f5b1cb4bb26 in __vmprof_eval_vmprof () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#60 0x00007f5b1bc7bcfd in pypy_g_CALL_FUNCTION_EX__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#61 0x00007f5b1bc80c8d in pypy_g_dispatch_bytecode__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#62 0x00007f5b1bc48872 in pypy_g_handle_bytecode__AccessDirect_None ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#63 0x00007f5b1c37f3d0 in pypy_g_portal_11 () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#64 0x00007f5b1c7629eb in pypy_g_ll_portal_runner__Unsigned_Bool_pypy_interpreter ()
   from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#65 0x00007f5b1bc0b86a in pypy_g_execute_frame () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#66 0x00007f5b1cb4bb26 in __vmprof_eval_vmprof () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#67 0x00007f5b1bbecba5 in pypy_g_call_function.star_3 () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#68 0x00007f5b1bbc0ac9 in pypy_g_entry_point () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#69 0x00007f5b1cc5e1af in pypy_main_startup () from /tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/libpypy3.10-c.so
#70 0x00007f5b1a623f0a in __libc_start_call_main (main=main@entry=0x401060 <main>, argc=argc@entry=11, argv=argv@entry=0x7ffddc93d678)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#71 0x00007f5b1a623fc5 in __libc_start_main_impl (main=0x401060 <main>, argc=11, argv=0x7ffddc93d678, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffddc93d668) at ../csu/libc-start.c:360
#72 0x000000000040108e in _start ()

```

The initial reproducer:

```
git clone https://github.com/google/brotli/
cd brotli
git checkout c8df4b3049ff1283fc4525defbcd003188f88963
/tmp/pypy-c-jit-107713-1775742c19f7-linux64/bin/pypy3.10 -m venv .venv
. .venv/bin/activate
pip install .
python -m unittest discover -s python -p "*_test.py" -vvf
```

c8df4b3049ff1283fc4525defbcd003188f88963 is the commit that introduced the problem upstream.  However, since acc265655d6dde4ff1bce65308e9e152fbf3381a upstream pypy crashes with a segfault instead — I don't know if it's related to the same problem or an independent regression.

Original bug report: https://github.com/google/brotli/issues/1072

**Comment by mattip** [comment]
@mgorny is this still a problem?

**Comment by mgorny** [comment]
Yes, I can reproduce with PyPy3.10 7.3.15:

```
test__test_compress_file_quality_11_lgwin_10_10x10y (tests.bro_test.TestBroCompress) ... RPython traceback:
  File "pypy_module_cpyext_1.c", line 8468, in wrapper_second_level__star_2_52
  File "implement.c", line 31693, in dispatcher_Py_22
Fatal RPython error: AssertionError
ERROR
```

**Comment by mattip** [comment]
This reproduces with pypy3.10-v7.3.16

There is a bit more information in the upstream bug report https://github.com/google/brotli/issues/1072
