### ISSUE TITLE
`datetime.datetime.now().replace(…)` fails when `now()` is mocked to a `datetime` object (botocore test suite)

### ISSUE THREAD

**Issue by mgorny** [pypy/pypy#4880]
Hit this in the wild in [botocore](https://github.com/boto/botocore). Could be related to #1187.

Reproducer:

```python
import datetime
import unittest.mock

DATE = datetime.datetime(2023, 11, 26, 0, 0, 0)

with unittest.mock.patch("datetime.datetime", spec=True) as mock_datetime:
    mock_datetime.now.return_value = DATE
    datetime.datetime.now().replace(hour=1)
```

Traceback:

```pytb
Traceback (most recent call last):
  File "/tmp/test.py", line 8, in <module>
    datetime.datetime.now().replace(hour=1)
  File "/usr/lib/pypy3.10/datetime.py", line 1866, in replace
    return datetime.__new__(
  File "/usr/lib/pypy3.10/unittest/mock.py", line 425, in __new__
    instance = _safe_super(NonCallableMock, cls).__new__(new)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: super(type, obj): obj must be an instance or subtype of type
```

Works in CPython 3.10.13.

**Comment by cfbolz** [comment]
It's the usual datetime mess again. the same bug appears in CPython if you block the import of `_datetime` or rewrite the reproducer to use `_pydatetime`. Here's essentially what's happening in even more condensed form:

```python
import unittest.mock

class Base:
    def replace(self):
        return 1

class A(Base):
    def replace(self):
        return super(self).replace()

    @staticmethod
    def now():
        return A()

DATE = A()

with unittest.mock.patch("__main__.A", spec=True) as mock_A:
    mock_A.now.return_value = DATE
    A.now().replace()
```

So it's not something we can easily fix in pypy (short of rewriting our datetime in rpython).

I'm trying to find a workaround that works on both pypy and cpython now.

**Comment by cfbolz** [comment]
here's an actual smaller reproducer that shows what's happening:

```python

import unittest.mock

class A:
    def replace(self):
        return A.__new__(type(self))

    @staticmethod
    def now():
        return A()

DATE = A()

with unittest.mock.patch("__main__.A", spec=True) as mock_A:
    mock_A.now.return_value = DATE
    A.now().replace()
```
