### ISSUE TITLE
Nightly pypy3.10 fails: `lib.SSL_get_error(ssl, retcode)`: TypeError: int() not supported on cdata 'size_t[1]'

### ISSUE THREAD

**Issue by nedbat** [pypy/pypy#4888]
I run the coverage.py test suite on PyPy nightlies.  The [last run failed](https://github.com/nedbat/coveragepy/actions/runs/7780959850/job/21222711130#step:4:103) during installation:
```
  Traceback (most recent call last):
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
      status = run_func(*args)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
      return func(self, options, args)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_internal/commands/install.py", line 419, in run
      requirement_set = resolver.resolve(
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
      result = self._result = resolver.resolve(
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
      state = resolution.resolve(requirements, max_rounds=max_rounds)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
      self._add_to_criteria(self.state.criteria, r, parent=None)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
      if not criterion.candidates:
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
      return bool(self._sequence)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
      return any(self)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
      return (c for c in iterator if id(c) not in self._incompatible_ids)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 44, in _iter_built
      for version, func in infos:
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 279, in iter_index_candidate_infos
      result = self._finder.find_best_candidate(
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_internal/index/package_finder.py", line 890, in find_best_candidate
      candidates = self.find_all_candidates(project_name)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_internal/index/package_finder.py", line 831, in find_all_candidates
      page_candidates = list(page_candidates_it)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_internal/index/sources.py", line 134, in page_candidates
      yield from self._candidates_from_page(self._link)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_internal/index/package_finder.py", line 791, in process_project_url
      index_response = self._link_collector.fetch_response(project_url)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_internal/index/collector.py", line 461, in fetch_response
      return _get_index_content(location, session=self.session)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_internal/index/collector.py", line 364, in _get_index_content
      resp = _get_simple_response(url, session=session)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_internal/index/collector.py", line 135, in _get_simple_response
      resp = session.get(
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_vendor/requests/sessions.py", line 600, in get
      return self.request("GET", url, **kwargs)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_internal/network/session.py", line 518, in request
      return super().request(method, url, *args, **kwargs)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_vendor/requests/sessions.py", line 587, in request
      resp = self.send(prep, **send_kwargs)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_vendor/requests/sessions.py", line 701, in send
      r = adapter.send(request, **kwargs)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_vendor/cachecontrol/adapter.py", line 57, in send
      resp = super(CacheControlAdapter, self).send(request, **kw)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_vendor/requests/adapters.py", line 489, in send
      resp = conn.urlopen(
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_vendor/urllib3/connectionpool.py", line 703, in urlopen
      httplib_response = self._make_request(
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_vendor/urllib3/connectionpool.py", line 449, in _make_request
      six.raise_from(e, None)
    File "<string>", line 3, in raise_from
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/site-packages/pip/_vendor/urllib3/connectionpool.py", line 444, in _make_request
      httplib_response = conn.getresponse()
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/http/client.py", line 1375, in getresponse
      response.begin()
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/http/client.py", line 318, in begin
      version, status, reason = self._read_status()
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/http/client.py", line 279, in _read_status
      line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/socket.py", line 705, in readinto
      return self._sock.recv_into(b)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/ssl.py", line 1329, in recv_into
      return self.read(nbytes, buffer)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/ssl.py", line 1163, in read
      return self._sslobj.read(len, buffer)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/_cffi_ssl/_stdssl/__init__.py", line 661, in read
      return self._read_buf(length, buffer_into)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/_cffi_ssl/_stdssl/__init__.py", line 748, in _read_buf
      err = _PySSL_errno(retval==0, self.ssl, count)
    File "/home/runner/work/_temp/121f1670-10f8-474e-8c2f-ff8a0af57f7d/pypy-c-jit-184356-1e45eee77938-linux64/lib/pypy3.10/_cffi_ssl/_stdssl/__init__.py", line 231, in _PySSL_errno
      err.ssl = lib.SSL_get_error(ssl, retcode)
  TypeError: int() not supported on cdata 'size_t[1]'
```

**Comment by nedbat** [comment]
Thanks!! No rush, my action will run again tomorrow.

**Comment by nedbat** [comment]
The nightlies passed today!
