### ISSUE TITLE
Discrepancy in handling `inspect.getfullargspec()` and `get.callargs()` for `dict` (ipywidgets)

### ISSUE THREAD

**Issue by mgorny** [pypy/pypy#4892]
Apparently, we have a discrepancy between how PyPy3.10 7.3.15 and CPython 3.10.13 `inspect` handles `dict` class. The affected functions are `getfullargspec()` and `callargs()`.

In CPython, both fail with `TypeError`:

```pytb
>>> inspect.getfullargspec(dict)
Traceback (most recent call last):
  File "/usr/lib/python3.10/inspect.py", line 1277, in getfullargspec
    sig = _signature_from_callable(func,
  File "/usr/lib/python3.10/inspect.py", line 2536, in _signature_from_callable
    raise ValueError(
ValueError: no signature found for builtin type <class 'dict'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/inspect.py", line 1287, in getfullargspec
    raise TypeError('unsupported callable') from ex
TypeError: unsupported callable
>>> inspect.getcallargs(dict, a="hello")
Traceback (most recent call last):
  File "/usr/lib/python3.10/inspect.py", line 1277, in getfullargspec
    sig = _signature_from_callable(func,
  File "/usr/lib/python3.10/inspect.py", line 2536, in _signature_from_callable
    raise ValueError(
ValueError: no signature found for builtin type <class 'dict'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/inspect.py", line 1493, in getcallargs
    spec = getfullargspec(func)
  File "/usr/lib/python3.10/inspect.py", line 1287, in getfullargspec
    raise TypeError('unsupported callable') from ex
TypeError: unsupported callable
```

In PyPy3.10, the former works but the latter does not:

```pytb
>>>> inspect.getfullargspec(dict)
FullArgSpec(args=['dicttype'], varargs='args', varkw='keywords', defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})
>>>> inspect.getcallargs(dict, a="hello")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/pypy3.10/inspect.py", line 1542, in getcallargs
    _missing_arguments(f_name, req, True, arg2value)
  File "/usr/lib/pypy3.10/inspect.py", line 1471, in _missing_arguments
    raise TypeError("%s() missing %i required %s argument%s: %s" %
TypeError: dict() missing 1 required positional argument: 'dicttype'
```

This is causing crashes in [ipywidgets](https://github.com/jupyter-widgets/ipywidgets/), since apparently it assumes that if the former didn't fail, the latter shouldn't either. The test suite output is:

```pytb
$ pypy3.10 -m pytest -vv --tb=long python/ipywidgets/ipywidgets/widgets/tests/test_interaction.py::test_interact_noinspect
========================================================= test session starts =========================================================
platform linux -- Python 3.10.13[pypy-7.3.15-final], pytest-8.0.0, pluggy-1.4.0 -- /usr/bin/pypy3.10
cachedir: .pytest_cache
rootdir: /tmp/ipywidgets/python/ipywidgets
plugins: xprocess-0.23.0, xdist-3.5.0, anyio-4.2.0, asyncio-0.23.4, subtests-0.11.0
asyncio: mode=strict
collected 1 item                                                                                                                      

python/ipywidgets/ipywidgets/widgets/tests/test_interaction.py::test_interact_noinspect FAILED                                  [100%]

============================================================== FAILURES ===============================================================
_______________________________________________________ test_interact_noinspect _______________________________________________________

    def test_interact_noinspect():
        a = 'hello'
>       c = interactive(dict, a=a)

python/ipywidgets/ipywidgets/widgets/tests/test_interaction.py:596: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = interactive(_dom_classes=('widget-interact',)), _interactive__interact_f = <class 'dict'>, _interactive__options = {}
kwargs = {}, f = <class 'dict'>, new_kwargs = [('a', 'hello', <class 'inspect._empty'>)]

    def __init__(self, __interact_f, __options={}, **kwargs):
        VBox.__init__(self, _dom_classes=['widget-interact'])
        self.result = None
        self.args = []
        self.kwargs = {}
    
        self.f = f = __interact_f
        self.clear_output = kwargs.pop('clear_output', True)
        self.manual = __options.get("manual", False)
        self.manual_name = __options.get("manual_name", "Run Interact")
        self.auto_display = __options.get("auto_display", False)
    
        new_kwargs = self.find_abbreviations(kwargs)
        # Before we proceed, let's make sure that the user has passed a set of args+kwargs
        # that will lead to a valid call of the function. This protects against unspecified
        # and doubly-specified arguments.
        try:
            check_argspec(f)
        except TypeError:
            # if we can't inspect, we can't validate
            pass
        else:
>           getcallargs(f, **{n:v for n,v,_ in new_kwargs})

python/ipywidgets/ipywidgets/widgets/interaction.py:182: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

func = <class 'dict'>, positional = (), named = {'a': 'hello'}
spec = FullArgSpec(args=['dicttype'], varargs='args', varkw='keywords', defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})
args = ['dicttype'], varargs = 'args', varkw = 'keywords', defaults = None, kwonlyargs = [], kwonlydefaults = None, ann = {}
f_name = 'dict', arg2value = {'args': (), 'keywords': {'a': 'hello'}}

    def getcallargs(func, /, *positional, **named):
        """Get the mapping of arguments to values.
    
        A dict is returned, with keys the function argument names (including the
        names of the * and ** arguments, if any), and values the respective bound
        values from 'positional' and 'named'."""
        spec = getfullargspec(func)
        args, varargs, varkw, defaults, kwonlyargs, kwonlydefaults, ann = spec
        f_name = func.__name__
        arg2value = {}
    
    
        if ismethod(func) and func.__self__ is not None:
            # implicit 'self' (or 'cls' for classmethods) argument
            positional = (func.__self__,) + positional
        num_pos = len(positional)
        num_args = len(args)
        num_defaults = len(defaults) if defaults else 0
    
        n = min(num_pos, num_args)
        for i in range(n):
            arg2value[args[i]] = positional[i]
        if varargs:
            arg2value[varargs] = tuple(positional[n:])
        possible_kwargs = set(args + kwonlyargs)
        if varkw:
            arg2value[varkw] = {}
        for kw, value in named.items():
            if kw not in possible_kwargs:
                if not varkw:
                    raise TypeError("%s() got an unexpected keyword argument %r" %
                                    (f_name, kw))
                arg2value[varkw][kw] = value
                continue
            if kw in arg2value:
                raise TypeError("%s() got multiple values for argument %r" %
                                (f_name, kw))
            arg2value[kw] = value
        if num_pos > num_args and not varargs:
            _too_many(f_name, args, kwonlyargs, varargs, num_defaults,
                       num_pos, arg2value)
        if num_pos < num_args:
            req = args[:num_args - num_defaults]
            for arg in req:
                if arg not in arg2value:
>                   _missing_arguments(f_name, req, True, arg2value)

/usr/lib/pypy3.10/inspect.py:1542: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

f_name = 'dict', argnames = ['dicttype'], pos = True, values = {'args': (), 'keywords': {'a': 'hello'}}

    def _missing_arguments(f_name, argnames, pos, values):
        names = [repr(name) for name in argnames if name not in values]
        missing = len(names)
        if missing == 1:
            s = names[0]
        elif missing == 2:
            s = "{} and {}".format(*names)
        else:
            tail = ", {} and {}".format(*names[-2:])
            del names[-2:]
            s = ", ".join(names) + tail
>       raise TypeError("%s() missing %i required %s argument%s: %s" %
                        (f_name, missing,
                          "positional" if pos else "keyword-only",
                          "" if missing == 1 else "s", s))
E       TypeError: dict() missing 1 required positional argument: 'dicttype'

/usr/lib/pypy3.10/inspect.py:1471: TypeError
========================================================== warnings summary ===========================================================
../../usr/lib/pypy3.10/site-packages/jupyter_client/connect.py:22
  /usr/lib/pypy3.10/site-packages/jupyter_client/connect.py:22: DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs
  given by the platformdirs library.  To remove this warning and
  see the appropriate new directories, set the environment variable
  `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
  The use of platformdirs will be the default in `jupyter_core` v6
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================================= short test summary info =======================================================
FAILED python/ipywidgets/ipywidgets/widgets/tests/test_interaction.py::test_interact_noinspect - TypeError: dict() missing 1 required positional argument: 'dicttype'
==================================================== 1 failed, 1 warning in 1.71s =====================================================
```

Please let me know if I should report this to ipywidgets upstream, or if it's something to be fixed in PyPy.

**Comment by mattip** [comment]
ping @cfbolz. Maybe we should revert the change to signatures?
