### ISSUE TITLE
Error using numpy under windows

### ISSUE THREAD

**Issue by DISKETR** [pypy/pypy#4929]
I use the pypy3.10. interpreter and installed numpy1.26.4 via pip. But I got an error when running the program. The following is the error message:<frozen importlib._bootstrap>:241: Warning: Numpy built with MINGW-W64 on Windows 64 bits is experimental, and only available for 
testing. You are advised not to use it for production. 

CRASHES ARE TO BE EXPECTED - PLEASE REPORT THEM TO NUMPY DEVELOPERS
D:\Program Files (x86)\environment\pypy3.10-v7.3.15-win64\lib\site-packages\numpy\core\getlimits.py:225: RuntimeWarning: invalid value encountered in exp2
  epsneg_f128 = exp2(ld(-113))
D:\Program Files (x86)\environment\pypy3.10-v7.3.15-win64\lib\site-packages\numpy\core\getlimits.py:226: RuntimeWarning: invalid value encountered in exp2
  tiny_f128 = exp2(ld(-16382))
D:\Program Files (x86)\environment\pypy3.10-v7.3.15-win64\lib\site-packages\numpy\core\getlimits.py:240: RuntimeWarning: invalid value encountered in exp2
  eps=exp2(ld(-112)),
D:\Program Files (x86)\environment\pypy3.10-v7.3.15-win64\lib\site-packages\numpy\core\getlimits.py:41: RuntimeWarning: invalid value encountered in nextafter
  self._smallest_subnormal = nextafter(
D:\Program Files (x86)\environment\pypy3.10-v7.3.15-win64\lib\site-packages\numpy\core\getlimits.py:52: RuntimeWarning: invalid value encountered in log10
  self.precision = int(-log10(self.eps))
How to fix this error? Does pypy support pandas?

**Comment by mattip** [comment]
Does this work correctly on regular python? This sounds a lot like https://github.com/numpy/numpy/issues/26038, is it related?

**Comment by DISKETR** [comment]
> Does this work correctly on regular python? This sounds a lot like [numpy/numpy#26038](https://github.com/numpy/numpy/issues/26038), is it related?

Yes, it can be run on ordinary python. It seems to be the same as the problem you mentioned. But I don’t know how to solve it. Is it a problem with the numpy version? I used git to install numpy, but when I imported numpy, I still got the same error.Also, I failed to install pandas.

**Comment by DISKETR** [comment]
This is the error that occurs when installing pandas：

C:\Users\Administrator>pypy -m pip install pandas
Collecting pandas
  Using cached pandas-2.2.1.tar.gz (4.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  脳 Preparing metadata (pyproject.toml) did not run successfully.
  鈹?exit code:  2
  鈺扳攢> [77 lines of output]
      + meson setup C:\Users\Administrator\AppData\Local\Temp\pip-install-80ixj37k\pandas_6ffe003d3ccb4f2a9f61c5aa0771515f C:\Users\Administrator\AppData\Local\Temp\pip-install-80ixj37k\pandas_6ffe003d3ccb4f2a9f61c5aa0771515f\.mesonpy-gqqamjqb\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=C:\Users\Administrator\AppData\Local\Temp\pip-install-80ixj37k\pandas_6ffe003d3ccb4f2a9f61c5aa0771515f\.mesonpy-gqqamjqb\build\meson-python-native-file.ini
      Exception in thread Thread-3 (_readerthread):
      Traceback (most recent call last):
        File "D:\Program Files (x86)\environment\pypy3.10-v7.3.15-win64\Lib\threading.py", line 1016, in _bootstrap_inner
          self.run()
        File "D:\Program Files (x86)\environment\pypy3.10-v7.3.15-win64\Lib\threading.py", line 953, in run
          self._target(*self._args, **self._kwargs)
        File "D:\Program Files (x86)\environment\pypy3.10-v7.3.15-win64\Lib\subprocess.py", line 1543, in _readerthread
          buffer.append(fh.read())
        File "D:\Program Files (x86)\environment\pypy3.10-v7.3.15-win64\Lib\codecs.py", line 322, in decode
          (result, consumed) = self._buffer_decode(data, self.errors, final)
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 19: invalid start byte
      Exception in thread Thread-4 (_readerthread):
      Traceback (most recent call last):
        File "D:\Program Files (x86)\environment\pypy3.10-v7.3.15-win64\Lib\threading.py", line 1016, in _bootstrap_inner
          self.run()
        File "D:\Program Files (x86)\environment\pypy3.10-v7.3.15-win64\Lib\threading.py", line 953, in run
          self._target(*self._args, **self._kwargs)
        File "D:\Program Files (x86)\environment\pypy3.10-v7.3.15-win64\Lib\subprocess.py", line 1543, in _readerthread
          buffer.append(fh.read())
        File "D:\Program Files (x86)\environment\pypy3.10-v7.3.15-win64\Lib\codecs.py", line 322, in decode
          (result, consumed) = self._buffer_decode(data, self.errors, final)
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
      Traceback (most recent call last):
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\mesonmain.py", line 194, in run
          return options.run_func(options)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\msetup.py", line 358, in run
          app.generate()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\msetup.py", line 183, in generate
          return self._generate(env, capture, vslite_ctx)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\msetup.py", line 205, in _generate
          intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 330, in __init__
          self.parse_project()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 134, in parse_project
          self.evaluate_codeblock(self.ast, end=1)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 196, in evaluate_statement
          return self.function_call(cur)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 521, in function_call
          res = func(node, func_args, kwargs)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
          return f(*nargs, **wrapped_kwargs)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 596, in wrapper
          return f(*wrapped_args, **wrapped_kwargs)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1310, in func_project
          self.add_languages(proj_langs, True, MachineChoice.HOST)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1467, in add_languages
          success = self.add_languages_for(args, required, for_machine)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1510, in add_languages_for
          comp = compilers.detect_compiler_for(self.environment, lang, for_machine, skip_sanity_check)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\compilers\detect.py", line 115, in detect_compiler_for
          comp = compiler_from_language(env, lang, for_machine)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\compilers\detect.py", line 112, in compiler_from_language
          return lang_map[lang](env, for_machine) if lang in lang_map else None
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\compilers\detect.py", line 614, in detect_c_compiler
          return _detect_c_or_cpp_compiler(env, 'c', for_machine)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\compilers\detect.py", line 330, in _detect_c_or_cpp_compiler
          p, out, err = Popen_safe_logged(cmd, msg='Detecting compiler via')
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-_fltqtlb\overlay\Lib\site-packages\mesonbuild\utils\universal.py", line 1529, in Popen_safe_logged
          rc, out, err = p.returncode, o.strip(), e.strip()
      AttributeError: 'NoneType' object has no attribute 'strip'
      The Meson build system
      Version: 1.2.1
      Source dir: C:\Users\Administrator\AppData\Local\Temp\pip-install-80ixj37k\pandas_6ffe003d3ccb4f2a9f61c5aa0771515f
      Build dir: C:\Users\Administrator\AppData\Local\Temp\pip-install-80ixj37k\pandas_6ffe003d3ccb4f2a9f61c5aa0771515f\.mesonpy-gqqamjqb\build
      Build type: native build
      Project name: pandas
      Project version: 2.2.1
      Activating VS 17.7.4

      ..\..\meson.build:2:0: ERROR: Unhandled python exception

          This is a Meson bug and should be reported!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

 Encountered error while generating package metadata.
> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by mattip** [comment]
We only test PyPy with MSVC. Do you have a clear use case for Pandas on PyPy? In most cases PyPy is slower since it needs to emulate CPython's C-API.

**Comment by DISKETR** [comment]
> 我们仅使用 MSVC 测试 PyPy。您对 PyPy 上的 Pandas 有明确的用例吗？在大多数情况下，PyPy 速度较慢，因为它需要模拟 CPython 的 C-API。

I just use it to read table data

**Comment by mattip** [comment]
PyPy on linux will always be better supported than windows, and windows with MSVC will be better supported than mingw.

**Comment by DISKETR** [comment]
> PyPy on linux will always be better supported than windows, and windows with MSVC will be better supported than mingw.

Is it Microsoft visual c++ build tools? Do I need to install it and add it to the environment variables? Try importing numpy again?
I'll try it, if it doesn't work I'll use linux

**Comment by Vivojay** [comment]
Hi, I have a similar issue, I tried reinstalling numpy from git (`pip install git+https://github.com/numpy/numpy.git`) to no luck...
The error i receive is same except i dont get any traceback it just instantly terminates the python REPL/script containint `import numpy` line.

I used `gcc.exe (Rev2, Built by MSYS2 project) 14.2.0` for installing.

This is the exact message:

> \<frozen importlib._bootstrap>:488: Warning: Numpy built with MINGW-W64 on Windows 64 bits is experimental, and only available for
testing. You are advised not to use it for production.
\
CRASHES ARE TO BE EXPECTED - PLEASE REPORT THEM TO NUMPY DEVELOPERS

Any solutions or workarounds yet?

**Comment by mattip** [comment]
1. Use MSVC, which can be downloaded and installed for free
2. Use wsl linux
3. Are you getting a warning or an error? If it is an error, try running under gdb
