### ISSUE TITLE
Error compile pypy in RHEL 8

### ISSUE THREAD

**Issue by flaajimi** [pypy/pypy#4955]
When i compiled in RHEL 8 i have this error :

[root@XXXXXXXXX pypy3.9-v7.3.16-src]# cd pypy/goal && python2 ../../rpython/bin/rpython -Ojit targetpypystandalone.py
[translation:info] 2.7.18 (default, Oct 3 2023, 08:47:34)
[GCC 8.5.0 20210514 (Red Hat 8.5.0-20)]
[platform:msg] Set platform with 'host' cc=None, using cc='gcc', version='Unknown'
[translation:info] Translating target as defined by targetpypystandalone
Traceback (most recent call last):
File "../../rpython/bin/rpython", line 20, in
main()
File "/home/XXXX/pypy3.9-v7.3.16-src/rpython/translator/goal/translate.py", line 219, in main
targetspec_dic, translateconfig, config, args = parse_options_and_load_target()
File "/home/XXXX/pypy3.9-v7.3.16-src/rpython/translator/goal/translate.py", line 155, in parse_options_and_load_target
targetspec_dic = load_target(targetspec)
File "/home/XXXX/pypy3.9-v7.3.16-src/rpython/translator/goal/translate.py", line 97, in load_target
mod = import(specname)
File "targetpypystandalone.py", line 7, in
from pypy.interpreter import gateway
File "/home/XXXX/pypy3.9-v7.3.16-src/pypy/interpreter/gateway.py", line 19, in
from pypy.interpreter.eval import Code
File "/home/XXXX/pypy3.9-v7.3.16-src/pypy/interpreter/eval.py", line 6, in
from pypy.interpreter.baseobjspace import W_Root
File "/home/XXXX/pypy3.9-v7.3.16-src/pypy/interpreter/baseobjspace.py", line 6, in
from rpython.rlib import jit, types, rutf8
File "/home/XXXX/pypy3.9-v7.3.16-src/rpython/rlib/rutf8.py", line 26, in
from rpython.rlib.unicodedata import unicodedb
File "/home/XXXX/pypy3.9-v7.3.16-src/rpython/rlib/unicodedata/init.py", line 4, in
from rpython.rlib.unicodedata import unicodedb_5_2_0 as unicodedb
File "/home/XXXX/pypy3.9-v7.3.16-src/rpython/rlib/unicodedata/unicodedb_5_2_0.py", line 6, in
from rpython.rlib.unicodedata.supportcode import (signed_ord, _all_short,
File "/home/XXXX/pypy3.9-v7.3.16-src/rpython/rlib/unicodedata/supportcode.py", line 2, in
from rpython.rtyper.lltypesystem.rffi import r_ushort, r_short
File "/home/XXXX/pypy3.9-v7.3.16-src/rpython/rtyper/lltypesystem/rffi.py", line 515, in
sizeof_c_type('__int128_t', ignore_errors=True)
File "/home/XXXX/pypy3.9-v7.3.16-src/rpython/rtyper/tool/rfficache.py", line 38, in sizeof_c_type
return sizeof_c_types([c_typename], **kwds)[0]
File "/home/XXXX/pypy3.9-v7.3.16-src/rpython/rtyper/tool/rfficache.py", line 45, in sizeof_c_types
answer = ask_gcc(question, **kwds)
File "/home/XXXX/pypy3.9-v7.3.16-src/rpython/rtyper/tool/rfficache.py", line 35, in ask_gcc
return build_executable_cache([c_file], eci, ignore_errors=ignore_errors)
File "/home/XXXX/pypy3.9-v7.3.16-src/rpython/tool/gcc_cache.py", line 28, in build_executable_cache
result = platform.execute(platform.compile(c_files, eci))
File "/home/XXXX/pypy3.9-v7.3.16-src/rpython/translator/platform/init.py", line 103, in execute
env)
File "/home/XXXX/pypy3.9-v7.3.16-src/rpython/tool/runsubprocess.py", line 21, in run_subprocess
return _run(executable, args, env, cwd)
File "/home/XXXX/pypy3.9-v7.3.16-src/rpython/tool/runsubprocess.py", line 115, in _run
raise OSError('%s: %s\nargs=%r' % (args[0], results[1], args))
OSError: /tmp/usession-release-pypy3.9-v7.3.16-0/gcctest: [Errno 13] Permission denied

**Comment by mattip** [comment]
What are the permissions on `/tmp/usession-release-pypy3.9-v7.3.16-0/gcctest`? It should be executable.

**Comment by flaajimi** [comment]
-rwxr-x---. 1 root root 18040 May 17 12:34 /tmp/usession-release-pypy3.9-v7.3.16-11/gcctest

**Comment by mattip** [comment]
What happens if you try to execute that file?

**Comment by flaajimi** [comment]
Abondonnée
