### ISSUE TITLE
benchmarks are failing on py3.9

### ISSUE THREAD

**Issue by mattip** [pypy/pypy#4985]
There have been 3 [failed runs](https://buildbot.pypy.org/builders/jit-benchmark-linux-x86-64) of py3.9 benchmarks (the ones that start at 11:00). The traceback is 
```
Traceback (most recent call last):
  File "/home/buildslave/build_dir/jit-benchmark-linux-x86-64/benchmarks/unladen_swallow/perf.py", line 1582, in main
    bench_result = func(base_cmd_prefix, changed_cmd_prefix, options)
  File "/home/buildslave/build_dir/jit-benchmark-linux-x86-64/benchmarks/benchmarks.py", line 20, in BM
    return SimpleBenchmark(Measure, *args, **kwds)
  File "/home/buildslave/build_dir/jit-benchmark-linux-x86-64/benchmarks/unladen_swallow/perf.py", line 463, in SimpleBenchmark
    *args, **kwargs)
  File "/home/buildslave/build_dir/jit-benchmark-linux-x86-64/benchmarks/benchmarks.py", line 16, in Measure
    return MeasureGeneric(python, options, bm_path, **opts)
  File "/home/buildslave/build_dir/jit-benchmark-linux-x86-64/benchmarks/unladen_swallow/perf.py", line 827, in MeasureGeneric
    inherit_env=options.inherit_env)
  File "/home/buildslave/build_dir/jit-benchmark-linux-x86-64/benchmarks/unladen_swallow/perf.py", line 783, in CallAndCaptureOutput
    (subproc.returncode, err))
RuntimeError: Benchmark died (returncode: 1): Traceback (most recent call last):
  File "/home/buildslave/build_dir/jit-benchmark-linux-x86-64/benchmarks/own/bm_chameleon.py", line 2, in <module>
    from chameleon import PageTemplate
  File "/home/buildslave/build_dir/jit-benchmark-linux-x86-64/benchmarks/lib/chameleon/src/chameleon/__init__.py", line 1, in <module>
    from .zpt.template import PageTemplate
  File "/home/buildslave/build_dir/jit-benchmark-linux-x86-64/benchmarks/lib/chameleon/src/chameleon/zpt/template.py", line 22, in <module>
    from ..template import BaseTemplate
  File "/home/buildslave/build_dir/jit-benchmark-linux-x86-64/benchmarks/lib/chameleon/src/chameleon/template.py", line 54, in <module>
    for name, version in get_package_versions():
  File "/home/buildslave/build_dir/jit-benchmark-linux-x86-64/benchmarks/lib/chameleon/src/chameleon/template.py", line 46, in get_package_versions
    distributions = importlib_metadata.packages_distributions().values()
AttributeError: module 'importlib.metadata' has no attribute 'packages_distributions'
```

which is fair since `packages_distributions` is new for Python3.10. It is coming from [here](https://foss.heptapod.net/pypy/benchmarks/-/blob/branch/default/lib/chameleon/src/chameleon/template.py?ref_type=heads#L46), which is gated on [`sys.version_info < (3, 8)`](https://foss.heptapod.net/pypy/benchmarks/-/blob/branch/default/lib/chameleon/src/chameleon/template.py?ref_type=heads#L15). I wonder what changed to make this fail only now? Did we have some patch to importlib.metadata that recently got removed?

**Comment by mattip** [comment]
Ahh, this crept when I made changes for python3.11. Fixed.
