### ISSUE TITLE
Crash with ast module on Windows

### ISSUE THREAD

**Issue by risuwwv** [pypy/pypy#4987]
The following makes pypy exit silently instead of throwing an exception:
```
import ast
ast.parse('for [ ] b 1.0')
```

This is on Windows 10, with
```
Python 3.10.14 (75b3de9d9035, Apr 21 2024, 13:13:38)
[PyPy 7.3.16 with MSC v.1929 64 bit (AMD64)] on win32
```

**Comment by devdanzin** [comment]
Segfaults on Linux too:
```
Python 3.10.14 (75b3de9d9035, Apr 21 2024, 10:54:48)
[PyPy 7.3.16 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import ast
>>>> ast.parse('for [ ] b 1.0')

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5b729ce in pypy_g_loop () from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
(gdb) bt
#0  0x00007ffff5b729ce in pypy_g_loop () from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
#1  0x00007ffff5b7338c in pypy_g_Parser_get_invalid_target ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
#2  0x00007ffff5b47d68 in pypy_g_PythonParser_invalid_for_target ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
#3  0x00007ffff5b5ba94 in pypy_g_PythonParser_for_stmt ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
#4  0x00007ffff5b6238f in pypy_g_PythonParser_compound_stmt ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
#5  0x00007ffff5b6308a in pypy_g_PythonParser_statement ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
#6  0x00007ffff5b63439 in pypy_g_PythonParser__loop1_11 ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
#7  0x00007ffff5b63654 in pypy_g_PythonParser_statements ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
#8  0x00007ffff5b6398d in pypy_g_PythonParser_file ()
```

**Comment by devdanzin** [comment]
Doesn't crash with:
```
Python 3.9.18 (9c4f8ef178b6, Jan 14 2024, 11:28:13)
[PyPy 7.3.15 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
```

There are changes in pypy/interpreter/pyparser/baserpypeg.py and pypy/interpreter/pyparser/rpypegparse.py that might account for that.

**Comment by risuwwv** [comment]
Thanks for having a look at this. I found one that has the same behaviour on that version on Windows:
```
 ast.parse('for [ ]')
```

With
```
Python 3.9.18 (9c4f8ef178b6, Jan 14 2024, 12:40:23)
[PyPy 7.3.15 with MSC v.1929 64 bit (AMD64)] on win32
```

**Comment by cfbolz** [comment]
both of these are fixed on the nightly 3.10. I think we shouldn't do a 3.9 release any more, @mattip, any thoughts?

**Comment by mattip** [comment]
It is tricky to drop 3.9 since that is the version being released on conda-forge. Is it difficult to find the 3.9 parsing problem?

**Comment by cfbolz** [comment]
ah, right, I keep forgetting about that aspect.

no, it's perfectly doable, just a little bit annoying. will get to it.

**Comment by cfbolz** [comment]
ok, I've backported it to py3.9 as well

**Comment by cfbolz** [comment]
closing the issue, please reopen it if necessary
