### ISSUE TITLE
The _curses module's exception crash on pypy

### ISSUE THREAD

**Issue by zzl261004** [pypy/pypy#4989]
Running this program on PyPy will result in a crash.

test.py
```
import _curses
_curses.initscr()
try:
    _curses.resizeterm(40000, 40000)
except:
    pass
_curses.initscr()

```

Behavior :
```
Segmentation fault (core dumped)
```

Environment:
Python 3.10.14 (75b3de9d9035,Apr 21 2024, 10:54:48) 
[PyPy 7.3.16 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Operating System: Ubuntu 18.04

**Comment by mattip** [comment]
On Ubuntu 22.04 with latest HEAD I get an error in `resizeterm`:
```
_curses.error: resizeterm() returned ERR
```

Is that where you are seeing the segfault? Ubuntu 18.04 is very old, perhaps try updating?

**Comment by zzl261004** [comment]
This is how I found the problem.Maybe the problem only exists in 18.04?
`root@90fd5300dad3:/tmp# pypy3.10 test.py
`
`Segmentation fault (core dumped)`

**Comment by devdanzin** [comment]
I can reproduce with 7.3.16 on WSL2/Ubuntu 22.04:
```
Python 3.10.14 (75b3de9d9035, Apr 21 2024, 10:54:48)
[PyPy 7.3.16 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
[...]
Platform: 'Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35'
On Linux: 'Ubuntu 22.04.4 LTS'
```
```
Program received signal SIGSEGV, Segmentation fault.
                                                    0x00007ffff42de1aa in ClrBottom () from /home/danzin/pypy3.10-v7.3.16-linux64/bin/../lib/libncursesw.so.6
(gdb) bt
#0  0x00007ffff42de1aa in ClrBottom ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/../lib/libncursesw.so.6
#1  0x00007ffff42e660a in doupdate_sp ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/../lib/libncursesw.so.6
#2  0x00007ffff42d7fc4 in wrefresh ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/../lib/libncursesw.so.6
#3  0x00007ffff4005e2c in ffi_call_unix64 ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/../lib/libffi.so.6
#4  0x00007ffff4005755 in ffi_call () from /home/danzin/pypy3.10-v7.3.16-linux64/bin/../lib/libffi.so.6
#5  0x00007ffff577105b in pypy_g_ccall_ffi_call__ffi_cifPtr_arrayPtr_arrayPtr_arr ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
#6  0x00007ffff6804831 in pypy_g_jit_ffi_call ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
#7  0x00007ffff5c30918 in pypy_g_W_CTypeFunc__call ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
#8  0x00007ffff595a38b in pypy_g_BuiltinCode_funcrun_obj ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
#9  0x00007ffff5a01815 in pypy_g_call_valuestack__AccessDirect_None ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
#10 0x00007ffff635f60d in pypy_g_CALL_METHOD__AccessDirect_star_1 ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
#11 0x00007ffff5a05e3d in pypy_g_dispatch_bytecode__AccessDirect_None ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
#12 0x00007ffff59ce832 in pypy_g_handle_bytecode__AccessDirect_None ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
#13 0x00007ffff612cb60 in pypy_g_portal_11 ()
   from /home/danzin/pypy3.10-v7.3.16-linux64/bin/libpypy3.10-c.so
```

Running without JIT still segfaults.

**Comment by mattip** [comment]
We faithfully track upstream CPython here: it too segfaults. I am inclined to close this as "don't do that".
