### ISSUE TITLE
JIT Causes test_cyclic_gc to Fail with function_threshold=1 in PyPy

### ISSUE THREAD

**Issue by zzl261004** [pypy/pypy#5019]
Hello PyPy team,

I'm encountering an issue with PyPy's JIT when running tests on a Python module. When JIT is enabled with the function_threshold=1 parameter, the test_cyclic_gc test in test.test_xml_etree.BasicElementTest fails. However, when JIT is disabled, all tests pass successfully. Below are the details:

program.py
```
import sys
import test.support

test.support.verbose = 1

def runtest(name):
    __import__(name)
    module = sys.modules[name]
    if hasattr(module, "test_main"):
        module.test_main()

runtest("test.test_xml_etree")
```

Run the script with JIT disabled(  pypy --jit off program.py  ):  
```
test_all (test.test_xml_etree.ModuleTest) ... ok
test_sanity (test.test_xml_etree.ModuleTest) ... ok
test_delslice (test.test_xml_etree.ElementSlicingTest) ... ok
test_getslice_negative_steps (test.test_xml_etree.ElementSlicingTest) ... ok
test_getslice_range (test.test_xml_etree.ElementSlicingTest) ... ok
test_getslice_single_index (test.test_xml_etree.ElementSlicingTest) ... ok
test_getslice_steps (test.test_xml_etree.ElementSlicingTest) ... ok
test_setslice_negative_steps (test.test_xml_etree.ElementSlicingTest) ... ok
test_setslice_range (test.test_xml_etree.ElementSlicingTest) ... ok
test_setslice_single_index (test.test_xml_etree.ElementSlicingTest) ... ok
test_setslice_steps (test.test_xml_etree.ElementSlicingTest) ... ok
test___copy__ (test.test_xml_etree.BasicElementTest) ... ok
test___deepcopy__ (test.test_xml_etree.BasicElementTest) ... ok
test___init__ (test.test_xml_etree.BasicElementTest) ... ok
test_augmentation_type_errors (test.test_xml_etree.BasicElementTest) ... ok
test_copy (test.test_xml_etree.BasicElementTest) ... ok
test_cyclic_gc (test.test_xml_etree.BasicElementTest) ... ok
test_get_keyword_args (test.test_xml_etree.BasicElementTest) ... ok
test_pickle (test.test_xml_etree.BasicElementTest) ... ok
test_pickle_issue18997 (test.test_xml_etree.BasicElementTest) ... ok
test_weakref (test.test_xml_etree.BasicElementTest) ... ok
test_ass_subscr (test.test_xml_etree.BadElementTest) ... ok
test_element_get_tail (test.test_xml_etree.BadElementTest) ... ok
test_element_get_text (test.test_xml_etree.BadElementTest) ... ok
test_extend_mutable_list (test.test_xml_etree.BadElementTest) ... ok
test_extend_mutable_list2 (test.test_xml_etree.BadElementTest) ... ok
test_recursive_repr (test.test_xml_etree.BadElementTest) ... ok
test_remove_with_mutating (test.test_xml_etree.BadElementTest) ... ok
test_subscr (test.test_xml_etree.BadElementTest) ... ok
test_treebuilder_end (test.test_xml_etree.BadElementTest) ... ok
test_treebuilder_start (test.test_xml_etree.BadElementTest) ... ok
test_find_with_error (test.test_xml_etree.BadElementPathTest) ... ok
test_find_with_mutating (test.test_xml_etree.BadElementPathTest) ... ok
test_findall_with_error (test.test_xml_etree.BadElementPathTest) ... ok
test_findall_with_mutating (test.test_xml_etree.BadElementPathTest) ... ok
test_findtext_with_error (test.test_xml_etree.BadElementPathTest) ... ok
test_findtext_with_mutating (test.test_xml_etree.BadElementPathTest) ... ok
test_attrib (test.test_xml_etree.ElementTreeTest) ... ok
test_cdata (test.test_xml_etree.ElementTreeTest) ... ok
test_children (test.test_xml_etree.ElementTreeTest) ... ok
test_copy (test.test_xml_etree.ElementTreeTest) ... ok
test_custom_builder (test.test_xml_etree.ElementTreeTest) ... ok
test_custom_builder_only_end_ns (test.test_xml_etree.ElementTreeTest) ... ok
test_doctype_public (test.test_xml_etree.ElementTreeTest) ... ok
test_dump_attribute_order (test.test_xml_etree.ElementTreeTest) ... ok
test_encoding (test.test_xml_etree.ElementTreeTest) ... ok
test_entity (test.test_xml_etree.ElementTreeTest) ... ok
test_file_init (test.test_xml_etree.ElementTreeTest) ... ok
test_html_empty_elems_serialization (test.test_xml_etree.ElementTreeTest) ... ok
test_indent (test.test_xml_etree.ElementTreeTest) ... ok
test_indent_level (test.test_xml_etree.ElementTreeTest) ... ok
test_indent_space (test.test_xml_etree.ElementTreeTest) ... ok
test_indent_space_caching (test.test_xml_etree.ElementTreeTest) ... ok
test_initialize_parser_without_target (test.test_xml_etree.ElementTreeTest) ... ok
test_interface (test.test_xml_etree.ElementTreeTest) ... ok
test_issue18347 (test.test_xml_etree.ElementTreeTest) ... ok
test_iterparse (test.test_xml_etree.ElementTreeTest) ... ok
test_makeelement (test.test_xml_etree.ElementTreeTest) ... ok
test_methods (test.test_xml_etree.ElementTreeTest) ... ok
test_namespace (test.test_xml_etree.ElementTreeTest) ... ok
test_parsefile (test.test_xml_etree.ElementTreeTest) ... ok
test_parseliteral (test.test_xml_etree.ElementTreeTest) ... ok
test_path_cache (test.test_xml_etree.ElementTreeTest) ... ok
test_processinginstruction (test.test_xml_etree.ElementTreeTest) ... ok
test_qname (test.test_xml_etree.ElementTreeTest) ... ok
test_set_attribute (test.test_xml_etree.ElementTreeTest) ... ok
test_simpleops (test.test_xml_etree.ElementTreeTest) ... ok
test_tostring_default_namespace (test.test_xml_etree.ElementTreeTest) ... ok
test_tostring_default_namespace_different_namespace (test.test_xml_etree.ElementTreeTest) ... ok
test_tostring_default_namespace_original_no_namespace (test.test_xml_etree.ElementTreeTest) ... ok
test_tostring_no_xml_declaration (test.test_xml_etree.ElementTreeTest) ... ok
test_tostring_xml_declaration (test.test_xml_etree.ElementTreeTest) ... ok
test_tostring_xml_declaration_cases (test.test_xml_etree.ElementTreeTest) ... ok
test_tostring_xml_declaration_unicode_encoding (test.test_xml_etree.ElementTreeTest) ... ok
test_tostringlist_default_namespace (test.test_xml_etree.ElementTreeTest) ... ok
test_tostringlist_xml_declaration (test.test_xml_etree.ElementTreeTest) ... ok
test_tree_write_attribute_order (test.test_xml_etree.ElementTreeTest) ... ok
test_writefile (test.test_xml_etree.ElementTreeTest) ... ok
test_writestring (test.test_xml_etree.ElementTreeTest) ... ok
test_xpath_tokenizer (test.test_xml_etree.ElementTreeTest) ... ok
test_encoding (test.test_xml_etree.IOTest) ... ok
test_read_from_bytesio (test.test_xml_etree.IOTest) ... ok
test_read_from_stringio (test.test_xml_etree.IOTest) ... ok
test_read_from_user_binary_reader (test.test_xml_etree.IOTest) ... ok
test_read_from_user_text_reader (test.test_xml_etree.IOTest) ... ok
test_short_empty_elements (test.test_xml_etree.IOTest) ... ok
test_tostringlist_invariant (test.test_xml_etree.IOTest) ... ok
test_write_to_binary_file (test.test_xml_etree.IOTest) ... ok
test_write_to_binary_file_with_bom (test.test_xml_etree.IOTest) ... ok
test_write_to_binary_file_with_encoding (test.test_xml_etree.IOTest) ... ok
test_write_to_bytesio (test.test_xml_etree.IOTest) ... ok
test_write_to_filename (test.test_xml_etree.IOTest) ... ok
test_write_to_filename_as_unicode (test.test_xml_etree.IOTest) ... ok
test_write_to_filename_with_encoding (test.test_xml_etree.IOTest) ... ok
test_write_to_stringio (test.test_xml_etree.IOTest) ... ok
test_write_to_text_file (test.test_xml_etree.IOTest) ... ok
test_write_to_user_binary_writer (test.test_xml_etree.IOTest) ... ok
test_write_to_user_binary_writer_with_bom (test.test_xml_etree.IOTest) ... ok
test_write_to_user_text_writer (test.test_xml_etree.IOTest) ... ok
test_error_code (test.test_xml_etree.ParseErrorTest) ... ok
test_error_position (test.test_xml_etree.ParseErrorTest) ... ok
test_subclass (test.test_xml_etree.ParseErrorTest) ... ok
test_xinclude (test.test_xml_etree.XIncludeTest) ... ok
test_xinclude_default (test.test_xml_etree.XIncludeTest) ... ok
test_xinclude_failures (test.test_xml_etree.XIncludeTest) ... ok
test_xinclude_repeated (test.test_xml_etree.XIncludeTest) ... ok
test_Element_subclass_constructor (test.test_xml_etree.ElementTreeTypeTest) ... ok
test_Element_subclass_find (test.test_xml_etree.ElementTreeTypeTest) ... ok
test_Element_subclass_new_method (test.test_xml_etree.ElementTreeTypeTest) ... ok
test_Element_subclass_trivial (test.test_xml_etree.ElementTreeTypeTest) ... ok
test_istype (test.test_xml_etree.ElementTreeTypeTest) ... ok
test_bad_find (test.test_xml_etree.ElementFindTest) ... ok
test_find_simple (test.test_xml_etree.ElementFindTest) ... ok
test_find_through_ElementTree (test.test_xml_etree.ElementFindTest) ... ok
test_find_xpath (test.test_xml_etree.ElementFindTest) ... ok
test_findall (test.test_xml_etree.ElementFindTest) ... ok
test_findall_different_nsmaps (test.test_xml_etree.ElementFindTest) ... ok
test_findall_wildcard (test.test_xml_etree.ElementFindTest) ... ok
test_test_find_with_ns (test.test_xml_etree.ElementFindTest) ... ok
test_basic (test.test_xml_etree.ElementIterTest) ... ok
test_copy (test.test_xml_etree.ElementIterTest) ... ok
test_corners (test.test_xml_etree.ElementIterTest) ... ok
test_iter_by_tag (test.test_xml_etree.ElementIterTest) ... ok
test_pickle (test.test_xml_etree.ElementIterTest) ... ok
test_builder_lookup_errors (test.test_xml_etree.TreeBuilderTest) ... ok
test_doctype (test.test_xml_etree.TreeBuilderTest) ... ok
test_dummy_builder (test.test_xml_etree.TreeBuilderTest) ... ok
test_element_factory (test.test_xml_etree.TreeBuilderTest) ... ok
test_element_factory_pure_python_subclass (test.test_xml_etree.TreeBuilderTest) ... ok
test_element_factory_subclass (test.test_xml_etree.TreeBuilderTest) ... ok
test_late_tail (test.test_xml_etree.TreeBuilderTest) ... ok
test_late_tail_mix_pi_comments (test.test_xml_etree.TreeBuilderTest) ... ok
test_subclass (test.test_xml_etree.TreeBuilderTest) ... ok
test_subclass_comment_pi (test.test_xml_etree.TreeBuilderTest) ... ok
test_treebuilder_comment (test.test_xml_etree.TreeBuilderTest) ... ok
test_treebuilder_elementfactory_none (test.test_xml_etree.TreeBuilderTest) ... ok
test_treebuilder_pi (test.test_xml_etree.TreeBuilderTest) ... ok
test_constructor_args (test.test_xml_etree.XMLParserTest) ... ok
test_doctype_warning (test.test_xml_etree.XMLParserTest) ... ok
test_inherited_doctype (test.test_xml_etree.XMLParserTest)
Ensure that ordinary usage is not deprecated (Issue 19176) ... ok
test_parse_string (test.test_xml_etree.XMLParserTest) ... ok
test_subclass (test.test_xml_etree.XMLParserTest) ... ok
test_subclass_doctype (test.test_xml_etree.XMLParserTest) ... ok
test_events (test.test_xml_etree.XMLPullParserTest) ... ok
test_events_comment (test.test_xml_etree.XMLPullParserTest) ... ok
test_events_pi (test.test_xml_etree.XMLPullParserTest) ... ok
test_events_sequence (test.test_xml_etree.XMLPullParserTest) ... ok
test_feed_while_iterating (test.test_xml_etree.XMLPullParserTest) ... ok
test_ns_events (test.test_xml_etree.XMLPullParserTest) ... ok
test_ns_events_start (test.test_xml_etree.XMLPullParserTest) ... ok
test_ns_events_start_end (test.test_xml_etree.XMLPullParserTest) ... ok
test_simple_xml (test.test_xml_etree.XMLPullParserTest) ... ok
test_simple_xml_with_ns (test.test_xml_etree.XMLPullParserTest) ... ok
test_unknown_event (test.test_xml_etree.XMLPullParserTest) ... ok
test_39495_treebuilder_start (test.test_xml_etree.BugsTest) ... ok
test_bug_1534630 (test.test_xml_etree.BugsTest) ... ok
test_bug_200708_close (test.test_xml_etree.BugsTest) ... ok
test_bug_200708_newline (test.test_xml_etree.BugsTest) ... ok
test_bug_200709_default_namespace (test.test_xml_etree.BugsTest) ... ok
test_bug_200709_element_comment (test.test_xml_etree.BugsTest) ... ok
test_bug_200709_element_insert (test.test_xml_etree.BugsTest) ... ok
test_bug_200709_iter_comment (test.test_xml_etree.BugsTest) ... ok
test_bug_200709_register_namespace (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit21 (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit25 (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit28 (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit39 (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit54 (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit55 (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit60 (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit62 (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit63 (test.test_xml_etree.BugsTest) ... skipped ''
test_bug_xmltoolkitX1 (test.test_xml_etree.BugsTest) ... ok
test_expat224_utf8_bug (test.test_xml_etree.BugsTest) ... ok
test_expat224_utf8_bug_file (test.test_xml_etree.BugsTest) ... ok
test_issue10777 (test.test_xml_etree.BugsTest) ... ok
test_issue6233 (test.test_xml_etree.BugsTest) ... ok
test_issue6565 (test.test_xml_etree.BugsTest) ... ok
test_lost_elem (test.test_xml_etree.BugsTest) ... skipped 'generators are not reentrant'
test_lost_tail (test.test_xml_etree.BugsTest) ... ok
test_lost_text (test.test_xml_etree.BugsTest) ... ok
test_issue14818 (test.test_xml_etree.KeywordArgsTest) ... ok
test_c14n_exclusion (test.test_xml_etree.C14NTest) ... ok
test_simple_roundtrip (test.test_xml_etree.C14NTest) ... ok
test_xml_c14n2 (test.test_xml_etree.C14NTest) ... skipped 'QName rewriting in XPath text is not supported in out_inNsContent_c14nPrefixQnameXpathElem'
skipped 'QName rewriting in XPath text is not supported in out_inNsContent_c14nQnameXpathElem'
skipped 'Redeclared namespace handling is not supported in out_inNsRedecl_c14nDefault'
skipped 'Redeclared namespace handling is not supported in out_inNsSuperfluous_c14nDefault'

----------------------------------------------------------------------
Ran 185 tests in 0.173s

OK (skipped=6)
```

Run the script with JIT enabled and function_threshold=1(  pypy --jit function_threshold=1 program.py  ):  
```
test_all (test.test_xml_etree.ModuleTest) ... ok
test_sanity (test.test_xml_etree.ModuleTest) ... ok
test_delslice (test.test_xml_etree.ElementSlicingTest) ... ok
test_getslice_negative_steps (test.test_xml_etree.ElementSlicingTest) ... ok
test_getslice_range (test.test_xml_etree.ElementSlicingTest) ... ok
test_getslice_single_index (test.test_xml_etree.ElementSlicingTest) ... ok
test_getslice_steps (test.test_xml_etree.ElementSlicingTest) ... ok
test_setslice_negative_steps (test.test_xml_etree.ElementSlicingTest) ... ok
test_setslice_range (test.test_xml_etree.ElementSlicingTest) ... ok
test_setslice_single_index (test.test_xml_etree.ElementSlicingTest) ... ok
test_setslice_steps (test.test_xml_etree.ElementSlicingTest) ... ok
test___copy__ (test.test_xml_etree.BasicElementTest) ... ok
test___deepcopy__ (test.test_xml_etree.BasicElementTest) ... ok
test___init__ (test.test_xml_etree.BasicElementTest) ... ok
test_augmentation_type_errors (test.test_xml_etree.BasicElementTest) ... ok
test_copy (test.test_xml_etree.BasicElementTest) ... ok
test_cyclic_gc (test.test_xml_etree.BasicElementTest) ... FAIL
test_get_keyword_args (test.test_xml_etree.BasicElementTest) ... ok
test_pickle (test.test_xml_etree.BasicElementTest) ... ok
test_pickle_issue18997 (test.test_xml_etree.BasicElementTest) ... ok
test_weakref (test.test_xml_etree.BasicElementTest) ... ok
test_ass_subscr (test.test_xml_etree.BadElementTest) ... ok
test_element_get_tail (test.test_xml_etree.BadElementTest) ... ok
test_element_get_text (test.test_xml_etree.BadElementTest) ... ok
test_extend_mutable_list (test.test_xml_etree.BadElementTest) ... ok
test_extend_mutable_list2 (test.test_xml_etree.BadElementTest) ... ok
test_recursive_repr (test.test_xml_etree.BadElementTest) ... ok
test_remove_with_mutating (test.test_xml_etree.BadElementTest) ... ok
test_subscr (test.test_xml_etree.BadElementTest) ... ok
test_treebuilder_end (test.test_xml_etree.BadElementTest) ... ok
test_treebuilder_start (test.test_xml_etree.BadElementTest) ... ok
test_find_with_error (test.test_xml_etree.BadElementPathTest) ... ok
test_find_with_mutating (test.test_xml_etree.BadElementPathTest) ... ok
test_findall_with_error (test.test_xml_etree.BadElementPathTest) ... ok
test_findall_with_mutating (test.test_xml_etree.BadElementPathTest) ... ok
test_findtext_with_error (test.test_xml_etree.BadElementPathTest) ... ok
test_findtext_with_mutating (test.test_xml_etree.BadElementPathTest) ... ok
test_attrib (test.test_xml_etree.ElementTreeTest) ... ok
test_cdata (test.test_xml_etree.ElementTreeTest) ... ok
test_children (test.test_xml_etree.ElementTreeTest) ... ok
test_copy (test.test_xml_etree.ElementTreeTest) ... ok
test_custom_builder (test.test_xml_etree.ElementTreeTest) ... ok
test_custom_builder_only_end_ns (test.test_xml_etree.ElementTreeTest) ... ok
test_doctype_public (test.test_xml_etree.ElementTreeTest) ... ok
test_dump_attribute_order (test.test_xml_etree.ElementTreeTest) ... ok
test_encoding (test.test_xml_etree.ElementTreeTest) ... ok
test_entity (test.test_xml_etree.ElementTreeTest) ... ok
test_file_init (test.test_xml_etree.ElementTreeTest) ... ok
test_html_empty_elems_serialization (test.test_xml_etree.ElementTreeTest) ... ok
test_indent (test.test_xml_etree.ElementTreeTest) ... ok
test_indent_level (test.test_xml_etree.ElementTreeTest) ... ok
test_indent_space (test.test_xml_etree.ElementTreeTest) ... ok
test_indent_space_caching (test.test_xml_etree.ElementTreeTest) ... ok
test_initialize_parser_without_target (test.test_xml_etree.ElementTreeTest) ... ok
test_interface (test.test_xml_etree.ElementTreeTest) ... ok
test_issue18347 (test.test_xml_etree.ElementTreeTest) ... ok
test_iterparse (test.test_xml_etree.ElementTreeTest) ... ok
test_makeelement (test.test_xml_etree.ElementTreeTest) ... ok
test_methods (test.test_xml_etree.ElementTreeTest) ... ok
test_namespace (test.test_xml_etree.ElementTreeTest) ... ok
test_parsefile (test.test_xml_etree.ElementTreeTest) ... ok
test_parseliteral (test.test_xml_etree.ElementTreeTest) ... ok
test_path_cache (test.test_xml_etree.ElementTreeTest) ... ok
test_processinginstruction (test.test_xml_etree.ElementTreeTest) ... ok
test_qname (test.test_xml_etree.ElementTreeTest) ... ok
test_set_attribute (test.test_xml_etree.ElementTreeTest) ... ok
test_simpleops (test.test_xml_etree.ElementTreeTest) ... ok
test_tostring_default_namespace (test.test_xml_etree.ElementTreeTest) ... ok
test_tostring_default_namespace_different_namespace (test.test_xml_etree.ElementTreeTest) ... ok
test_tostring_default_namespace_original_no_namespace (test.test_xml_etree.ElementTreeTest) ... ok
test_tostring_no_xml_declaration (test.test_xml_etree.ElementTreeTest) ... ok
test_tostring_xml_declaration (test.test_xml_etree.ElementTreeTest) ... ok
test_tostring_xml_declaration_cases (test.test_xml_etree.ElementTreeTest) ... ok
test_tostring_xml_declaration_unicode_encoding (test.test_xml_etree.ElementTreeTest) ... ok
test_tostringlist_default_namespace (test.test_xml_etree.ElementTreeTest) ... ok
test_tostringlist_xml_declaration (test.test_xml_etree.ElementTreeTest) ... ok
test_tree_write_attribute_order (test.test_xml_etree.ElementTreeTest) ... ok
test_writefile (test.test_xml_etree.ElementTreeTest) ... ok
test_writestring (test.test_xml_etree.ElementTreeTest) ... ok
test_xpath_tokenizer (test.test_xml_etree.ElementTreeTest) ... ok
test_encoding (test.test_xml_etree.IOTest) ... ok
test_read_from_bytesio (test.test_xml_etree.IOTest) ... ok
test_read_from_stringio (test.test_xml_etree.IOTest) ... ok
test_read_from_user_binary_reader (test.test_xml_etree.IOTest) ... ok
test_read_from_user_text_reader (test.test_xml_etree.IOTest) ... ok
test_short_empty_elements (test.test_xml_etree.IOTest) ... ok
test_tostringlist_invariant (test.test_xml_etree.IOTest) ... ok
test_write_to_binary_file (test.test_xml_etree.IOTest) ... ok
test_write_to_binary_file_with_bom (test.test_xml_etree.IOTest) ... ok
test_write_to_binary_file_with_encoding (test.test_xml_etree.IOTest) ... ok
test_write_to_bytesio (test.test_xml_etree.IOTest) ... ok
test_write_to_filename (test.test_xml_etree.IOTest) ... ok
test_write_to_filename_as_unicode (test.test_xml_etree.IOTest) ... ok
test_write_to_filename_with_encoding (test.test_xml_etree.IOTest) ... ok
test_write_to_stringio (test.test_xml_etree.IOTest) ... ok
test_write_to_text_file (test.test_xml_etree.IOTest) ... ok
test_write_to_user_binary_writer (test.test_xml_etree.IOTest) ... ok
test_write_to_user_binary_writer_with_bom (test.test_xml_etree.IOTest) ... ok
test_write_to_user_text_writer (test.test_xml_etree.IOTest) ... ok
test_error_code (test.test_xml_etree.ParseErrorTest) ... ok
test_error_position (test.test_xml_etree.ParseErrorTest) ... ok
test_subclass (test.test_xml_etree.ParseErrorTest) ... ok
test_xinclude (test.test_xml_etree.XIncludeTest) ... ok
test_xinclude_default (test.test_xml_etree.XIncludeTest) ... ok
test_xinclude_failures (test.test_xml_etree.XIncludeTest) ... ok
test_xinclude_repeated (test.test_xml_etree.XIncludeTest) ... ok
test_Element_subclass_constructor (test.test_xml_etree.ElementTreeTypeTest) ... ok
test_Element_subclass_find (test.test_xml_etree.ElementTreeTypeTest) ... ok
test_Element_subclass_new_method (test.test_xml_etree.ElementTreeTypeTest) ... ok
test_Element_subclass_trivial (test.test_xml_etree.ElementTreeTypeTest) ... ok
test_istype (test.test_xml_etree.ElementTreeTypeTest) ... ok
test_bad_find (test.test_xml_etree.ElementFindTest) ... ok
test_find_simple (test.test_xml_etree.ElementFindTest) ... ok
test_find_through_ElementTree (test.test_xml_etree.ElementFindTest) ... ok
test_find_xpath (test.test_xml_etree.ElementFindTest) ... ok
test_findall (test.test_xml_etree.ElementFindTest) ... ok
test_findall_different_nsmaps (test.test_xml_etree.ElementFindTest) ... ok
test_findall_wildcard (test.test_xml_etree.ElementFindTest) ... ok
test_test_find_with_ns (test.test_xml_etree.ElementFindTest) ... ok
test_basic (test.test_xml_etree.ElementIterTest) ... ok
test_copy (test.test_xml_etree.ElementIterTest) ... ok
test_corners (test.test_xml_etree.ElementIterTest) ... ok
test_iter_by_tag (test.test_xml_etree.ElementIterTest) ... ok
test_pickle (test.test_xml_etree.ElementIterTest) ... ok
test_builder_lookup_errors (test.test_xml_etree.TreeBuilderTest) ... ok
test_doctype (test.test_xml_etree.TreeBuilderTest) ... ok
test_dummy_builder (test.test_xml_etree.TreeBuilderTest) ... ok
test_element_factory (test.test_xml_etree.TreeBuilderTest) ... ok
test_element_factory_pure_python_subclass (test.test_xml_etree.TreeBuilderTest) ... ok
test_element_factory_subclass (test.test_xml_etree.TreeBuilderTest) ... ok
test_late_tail (test.test_xml_etree.TreeBuilderTest) ... ok
test_late_tail_mix_pi_comments (test.test_xml_etree.TreeBuilderTest) ... ok
test_subclass (test.test_xml_etree.TreeBuilderTest) ... ok
test_subclass_comment_pi (test.test_xml_etree.TreeBuilderTest) ... ok
test_treebuilder_comment (test.test_xml_etree.TreeBuilderTest) ... ok
test_treebuilder_elementfactory_none (test.test_xml_etree.TreeBuilderTest) ... ok
test_treebuilder_pi (test.test_xml_etree.TreeBuilderTest) ... ok
test_constructor_args (test.test_xml_etree.XMLParserTest) ... ok
test_doctype_warning (test.test_xml_etree.XMLParserTest) ... ok
test_inherited_doctype (test.test_xml_etree.XMLParserTest)
Ensure that ordinary usage is not deprecated (Issue 19176) ... ok
test_parse_string (test.test_xml_etree.XMLParserTest) ... ok
test_subclass (test.test_xml_etree.XMLParserTest) ... ok
test_subclass_doctype (test.test_xml_etree.XMLParserTest) ... ok
test_events (test.test_xml_etree.XMLPullParserTest) ... ok
test_events_comment (test.test_xml_etree.XMLPullParserTest) ... ok
test_events_pi (test.test_xml_etree.XMLPullParserTest) ... ok
test_events_sequence (test.test_xml_etree.XMLPullParserTest) ... ok
test_feed_while_iterating (test.test_xml_etree.XMLPullParserTest) ... ok
test_flush_reparse_deferral_disabled (test.test_xml_etree.XMLPullParserTest) ... ok
test_flush_reparse_deferral_enabled (test.test_xml_etree.XMLPullParserTest) ... ok
test_ns_events (test.test_xml_etree.XMLPullParserTest) ... ok
test_ns_events_start (test.test_xml_etree.XMLPullParserTest) ... ok
test_ns_events_start_end (test.test_xml_etree.XMLPullParserTest) ... ok
test_simple_xml (test.test_xml_etree.XMLPullParserTest) ... ok
test_simple_xml_chunk_1 (test.test_xml_etree.XMLPullParserTest) ... ok
test_simple_xml_chunk_22 (test.test_xml_etree.XMLPullParserTest) ... ok
test_simple_xml_chunk_5 (test.test_xml_etree.XMLPullParserTest) ... ok
test_simple_xml_with_ns (test.test_xml_etree.XMLPullParserTest) ... ok
test_unknown_event (test.test_xml_etree.XMLPullParserTest) ... ok
test_39495_treebuilder_start (test.test_xml_etree.BugsTest) ... ok
test_bug_1534630 (test.test_xml_etree.BugsTest) ... ok
test_bug_200708_close (test.test_xml_etree.BugsTest) ... ok
test_bug_200708_newline (test.test_xml_etree.BugsTest) ... ok
test_bug_200709_default_namespace (test.test_xml_etree.BugsTest) ... ok
test_bug_200709_element_comment (test.test_xml_etree.BugsTest) ... ok
test_bug_200709_element_insert (test.test_xml_etree.BugsTest) ... ok
test_bug_200709_iter_comment (test.test_xml_etree.BugsTest) ... ok
test_bug_200709_register_namespace (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit21 (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit25 (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit28 (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit39 (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit54 (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit55 (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit60 (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit62 (test.test_xml_etree.BugsTest) ... ok
test_bug_xmltoolkit63 (test.test_xml_etree.BugsTest) ... skipped ''
test_bug_xmltoolkitX1 (test.test_xml_etree.BugsTest) ... ok
test_expat224_utf8_bug (test.test_xml_etree.BugsTest) ... ok
test_expat224_utf8_bug_file (test.test_xml_etree.BugsTest) ... ok
test_issue10777 (test.test_xml_etree.BugsTest) ... ok
test_issue6233 (test.test_xml_etree.BugsTest) ... ok
test_issue6565 (test.test_xml_etree.BugsTest) ... ok
test_lost_elem (test.test_xml_etree.BugsTest) ... skipped 'generators are not reentrant'
test_lost_tail (test.test_xml_etree.BugsTest) ... ok
test_lost_text (test.test_xml_etree.BugsTest) ... ok
test_issue14818 (test.test_xml_etree.KeywordArgsTest) ... ok
test_c14n_exclusion (test.test_xml_etree.C14NTest) ... ok
test_simple_roundtrip (test.test_xml_etree.C14NTest) ... ok
test_xml_c14n2 (test.test_xml_etree.C14NTest) ... skipped 'QName rewriting in XPath text is not supported in out_inNsContent_c14nPrefixQnameXpathElem'
skipped 'QName rewriting in XPath text is not supported in out_inNsContent_c14nQnameXpathElem'
skipped 'Redeclared namespace handling is not supported in out_inNsRedecl_c14nDefault'
skipped 'Redeclared namespace handling is not supported in out_inNsSuperfluous_c14nDefault'

======================================================================
FAIL: test_cyclic_gc (test.test_xml_etree.BasicElementTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pypy3.9-v7.3.16-linux64/lib/pypy3.9/test/test_xml_etree.py", line 2498, in test_cyclic_gc
    self.assertIsNone(wref())
AssertionError: <test.test_xml_etree.BasicElementTest.test_cyclic_gc.<locals>.Dummy object at 0x00000000075ba720> is not None

----------------------------------------------------------------------
Ran 190 tests in 4.719s

FAILED (failures=1, skipped=6)
Traceback (most recent call last):
  File "/tmp/nowtest/log3/program.py", line 13, in <module>
    runtest("test.test_xml_etree")
  File "/tmp/nowtest/log3/program.py", line 12, in runtest
    module.test_main()
  File "/opt/pypy3.9-v7.3.16-linux64/lib/pypy3.9/test/test_xml_etree.py", line 4274, in test_main
    support.run_unittest(*test_classes)
  File "/opt/pypy3.9-v7.3.16-linux64/lib/pypy3.9/test/support/__init__.py", line 1976, in run_unittest
    _run_suite(suite)
  File "/opt/pypy3.9-v7.3.16-linux64/lib/pypy3.9/test/support/__init__.py", line 1869, in _run_suite
    raise TestFailedWithDetails(err, errors, failures)
test.support.TestFailedWithDetails: Traceback (most recent call last):
  File "/opt/pypy3.9-v7.3.16-linux64/lib/pypy3.9/test/test_xml_etree.py", line 2498, in test_cyclic_gc
    self.assertIsNone(wref())
AssertionError: <test.test_xml_etree.BasicElementTest.test_cyclic_gc.<locals>.Dummy object at 0x00000000075ba720> is not None

```

Environment:
Python 3.9.19 (a2113ea87262, Apr 21 2024, 05:40:24)
[PyPy 7.3.16 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Operating System: Ubuntu 22.04.4 LTS

**Comment by cfbolz** [comment]
that is hard to fix. `function_threshold=1` means that the `test_cyclic_gc` function is traced on the very first execution, and tracing will definitely keep objects alive a little bit longer. Therefore the weakrefs don't die during the test (but they will die immediately after the test function finishes and tracing is done). Extending the lifetime of objects a little bit is an acceptable effect of tracing, imo. Outside of tests that check lifetimes specifically, "normal" code would very likely never care.
