### ISSUE TITLE
Issue installing cffi related packages on windows

### ISSUE THREAD

**Issue by Miauwkeru** [pypy/pypy#5027]
Hello, I do not know whether you all where aware, but I noticed yesterday that one of the windows pipelines we use for our projects are failing with pypy 

Affected pypy versions that our pipeline uses:
> pypy3.9
> pypy3.10

Affected operating systems:
> Windows

The error in our pipeline occurs when trying to install `argon-cffi` where it attempts to use the deprecated `distutils.msvc9compiler` module. This version uses a `try/catch` function in `cffi==1.17.1` that I tried to use to fix this issue. As applying the [following patch](https://github.com/python-cffi/cffi/commit/5982be1aebccaaea73b5b4cb171bc9214f8e994d) to pypy's internal cffi library did fix it locally. However, pypy uses its internal library one instead. 

<details>

```
pypy3.10: install_deps> python -I -m pip install cffi==1.17.1 coverage pytest pytest-cov
.pkg: install_requires> python -I -m pip install setuptools>=65.5.0 setuptools_scm[toml]>=6.4.0
.pkg: _optional_hooks> python C:\hostedtoolcache\windows\PyPy\3.10.14\x86\lib\site-packages\pyproject_api\_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_sdist> python C:\hostedtoolcache\windows\PyPy\3.10.14\x86\lib\site-packages\pyproject_api\_backend.py True setuptools.build_meta
.pkg: freeze> python -m pip freeze --all
.pkg: cffi==1.17.0,greenlet==0.4.13,hpy==0.9.0,packaging==24.1,pip==24.1,readline==6.2.4.1,setuptools==70.1.0,setuptools-scm==8.1.0,tomli==2.0.1,wheel==0.43.0
.pkg: build_sdist> python C:\hostedtoolcache\windows\PyPy\3.10.14\x86\lib\site-packages\pyproject_api\_backend.py True setuptools.build_meta
pypy3.10: install_package_deps> python -I -m pip install dissect.cstruct<5,>=4 dissect.cstruct<5.0.dev,>=4.0.dev dissect.target<4,>=3.7 dissect.target[dev]<4.0.dev,>=3.7.dev dissect.target[full]<4,>=3.7 minio pycryptodome requests requests_toolbelt rich
Collecting dissect.cstruct<5,>=4

  Downloading dissect.cstruct-4.0-py3-none-any.whl.metadata (8.6 kB)
  error: subprocess-exited-with-error

  

  × Preparing metadata (pyproject.toml) did not run successfully.

  │ exit code: 1

  ╰─> [44 lines of output]

      Traceback (most recent call last):

        File "C:\hostedtoolcache\windows\PyPy\3.10.14\x86\Lib\cffi\_shimmed_dist_utils.py", line 33, in <module>

          from distutils.msvc9compiler import MSVCCompiler

      ModuleNotFoundError: No module named 'distutils.msvc9compiler'

      

      The above exception was the direct cause of the following exception:

      

      Traceback (most recent call last):

        File "D:\a\acquire\acquire\.tox\pypy3.10\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>

          main()

        File "D:\a\acquire\acquire\.tox\pypy3.10\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main

          json_out['return_val'] = hook(**hook_input['kwargs'])

                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        File "D:\a\acquire\acquire\.tox\pypy3.10\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel

          return hook(metadata_directory, config_settings)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-uasgl4p1\overlay\Lib\site-packages\setuptools\build_meta.py", line 373, in prepare_metadata_for_build_wheel

          self.run_setup()

        File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-uasgl4p1\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup

          exec(code, locals())

        File "<string>", line 86, in <module>

        File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-uasgl4p1\overlay\Lib\site-packages\setuptools\__init__.py", line 117, in setup

          return distutils.core.setup(**attrs)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-uasgl4p1\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 146, in setup

          _setup_distribution = dist = klass(attrs)

                                       ^^^^^^^^^^^^

        File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-uasgl4p1\overlay\Lib\site-packages\setuptools\dist.py", line 283, in __init__

          _Distribution.__init__(self, dist_attrs)

        File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-uasgl4p1\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 279, in __init__

          self.finalize_options()

        File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-uasgl4p1\overlay\Lib\site-packages\setuptools\dist.py", line 635, in finalize_options

          ep(self)

        File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-uasgl4p1\overlay\Lib\site-packages\setuptools\dist.py", line 655, in _finalize_setup_keywords

          ep.load()(self, ep.name, value)

        File "C:\hostedtoolcache\windows\PyPy\3.10.14\x86\Lib\cffi\setuptools_ext.py", line 216, in cffi_modules

          add_cffi_module(dist, cffi_module)

        File "C:\hostedtoolcache\windows\PyPy\3.10.14\x86\Lib\cffi\setuptools_ext.py", line 71, in add_cffi_module

          _add_c_module(dist, ffi, module_name, source, source_extension, kwds)

        File "C:\hostedtoolcache\windows\PyPy\3.10.14\x86\Lib\cffi\setuptools_ext.py", line 109, in _add_c_module

          from cffi._shimmed_dist_utils import Extension, log, mkpath

        File "C:\hostedtoolcache\windows\PyPy\3.10.14\x86\Lib\cffi\_shimmed_dist_utils.py", line 39, in <module>

          raise Exception("This CFFI feature requires distutils. Please install the distutils or setuptools package.") from ex

      Exception: This CFFI feature requires distutils. Please install the distutils or setuptools package.

      [end of output]

  

  note: This error originates from a subprocess, and is likely not a problem with pip.

error: metadata-generation-failed



× Encountered error while generating package metadata.

╰─> See above for output.



note: This is an issue with the package mentioned above, not pip.

hint: See above for details.


  Downloading dissect.cstruct-4.1.dev1-py3-none-any.whl.metadata (8.6 kB)

Collecting dissect.target<4,>=3.7

  Downloading dissect.target-3.18-py3-none-any.whl.metadata (12 kB)

  Downloading dissect.target-3.19.dev53-py3-none-any.whl.metadata (12 kB)

Collecting minio

  Downloading minio-7.2.8-py3-none-any.whl.metadata (6.5 kB)

Collecting pycryptodome

  Downloading pycryptodome-3.20.0-pp310-pypy310_pp73-win_amd64.whl.metadata (3.5 kB)

Collecting requests

  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)

Collecting requests_toolbelt

  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)

Collecting rich

  Downloading rich-13.8.0-py3-none-any.whl.metadata (18 kB)

Collecting defusedxml (from dissect.target<4,>=3.7)

  Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)

Collecting dissect.eventlog<4,>=3 (from dissect.target<4,>=3.7)

  Downloading dissect.eventlog-3.9-py3-none-any.whl.metadata (3.2 kB)

Collecting dissect.evidence<4,>=3 (from dissect.target<4,>=3.7)

  Downloading dissect.evidence-3.10-py3-none-any.whl.metadata (3.3 kB)

Collecting dissect.hypervisor<4,>=3 (from dissect.target<4,>=3.7)

  Downloading dissect.hypervisor-3.14-py3-none-any.whl.metadata (3.5 kB)

Collecting dissect.ntfs<4,>=3.4 (from dissect.target<4,>=3.7)

  Downloading dissect.ntfs-3.11-py3-none-any.whl.metadata (3.2 kB)

Collecting dissect.regf<4,>=3.3 (from dissect.target<4,>=3.7)

  Downloading dissect.regf-3.11-py3-none-any.whl.metadata (3.3 kB)

Collecting dissect.util<4,>=3 (from dissect.target<4,>=3.7)

  Downloading dissect.util-3.17-py3-none-any.whl.metadata (3.0 kB)

Collecting dissect.volume<4,>=2 (from dissect.target<4,>=3.7)

  Downloading dissect.volume-3.11-py3-none-any.whl.metadata (3.3 kB)

Collecting flow.record~=3.15.0 (from dissect.target<4,>=3.7)

  Downloading flow.record-3.15-py3-none-any.whl.metadata (6.3 kB)

Collecting structlog (from dissect.target<4,>=3.7)

  Downloading structlog-24.4.0-py3-none-any.whl.metadata (7.3 kB)

Collecting certifi (from minio)

  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)

Collecting urllib3 (from minio)

  Downloading urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)

Collecting argon2-cffi (from minio)

  Downloading argon2_cffi-23.1.0-py3-none-any.whl.metadata (5.2 kB)

Collecting typing-extensions (from minio)

  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)

Collecting charset-normalizer<4,>=2 (from requests)

  Downloading charset_normalizer-3.3.2-py3-none-any.whl.metadata (33 kB)

Collecting idna<4,>=2.5 (from requests)

  Downloading idna-3.8-py3-none-any.whl.metadata (9.9 kB)

Collecting markdown-it-py>=2.2.0 (from rich)

  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)

Collecting pygments<3.0.0,>=2.13.0 (from rich)

  Downloading pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)

Collecting dissect.btrfs<2.0.dev,>=1.0.dev (from dissect.btrfs[dev]<2.0.dev,>=1.0.dev; extra == "dev"->dissect.target[dev]<4.0.dev,>=3.7.dev)

  Downloading dissect.btrfs-1.5.dev1-py3-none-any.whl.metadata (4.0 kB)

Collecting dissect.cim<4.0.dev,>=3.0.dev (from dissect.cim[dev]<4.0.dev,>=3.0.dev; extra == "dev"->dissect.target[dev]<4.0.dev,>=3.7.dev)

  Downloading dissect.cim-3.10-py3-none-any.whl.metadata (3.3 kB)

Collecting dissect.clfs<2.0.dev,>=1.0.dev (from dissect.clfs[dev]<2.0.dev,>=1.0.dev; extra == "dev"->dissect.target[dev]<4.0.dev,>=3.7.dev)

  Downloading dissect.clfs-1.9-py3-none-any.whl.metadata (3.2 kB)

Collecting dissect.esedb<4.0.dev,>=3.0.dev (from dissect.esedb[dev]<4.0.dev,>=3.0.dev; extra == "dev"->dissect.target[dev]<4.0.dev,>=3.7.dev)

  Downloading dissect.esedb-3.14-py3-none-any.whl.metadata (3.9 kB)

Collecting dissect.etl<4.0.dev,>=3.0.dev (from dissect.etl[dev]<4.0.dev,>=3.0.dev; extra == "dev"->dissect.target[dev]<4.0.dev,>=3.7.dev)

  Downloading dissect.etl-3.10-py3-none-any.whl.metadata (3.3 kB)

Collecting dissect.extfs<4.0.dev,>=3.0.dev (from dissect.extfs[dev]<4.0.dev,>=3.0.dev; extra == "dev"->dissect.target[dev]<4.0.dev,>=3.7.dev)

  Downloading dissect.extfs-3.11-py3-none-any.whl.metadata (3.3 kB)

Collecting dissect.fat<4.0.dev,>=3.0.dev (from dissect.fat[dev]<4.0.dev,>=3.0.dev; extra == "dev"->dissect.target[dev]<4.0.dev,>=3.7.dev)

  Downloading dissect.fat-3.10-py3-none-any.whl.metadata (3.3 kB)

Collecting dissect.ffs<4.0.dev,>=3.0.dev (from dissect.ffs[dev]<4.0.dev,>=3.0.dev; extra == "dev"->dissect.target[dev]<4.0.dev,>=3.7.dev)

  Downloading dissect.ffs-3.9-py3-none-any.whl.metadata (3.2 kB)

Collecting dissect.hypervisor<4,>=3 (from dissect.target<4,>=3.7)

  Downloading dissect.hypervisor-3.15.dev1-py3-none-any.whl.metadata (3.5 kB)

Collecting dissect.jffs<2.0.dev,>=1.0.dev (from dissect.jffs[dev]<2.0.dev,>=1.0.dev; extra == "dev"->dissect.target[dev]<4.0.dev,>=3.7.dev)

  Downloading dissect.jffs-1.3-py3-none-any.whl.metadata (2.8 kB)

Collecting dissect.ntfs<4,>=3.4 (from dissect.target<4,>=3.7)

  Downloading dissect.ntfs-3.12.dev1-py3-none-any.whl.metadata (3.2 kB)

Collecting dissect.shellitem<4.0.dev,>=3.0.dev (from dissect.shellitem[dev]<4.0.dev,>=3.0.dev; extra == "dev"->dissect.target[dev]<4.0.dev,>=3.7.dev)

  Downloading dissect.shellitem-3.9-py3-none-any.whl.metadata (3.3 kB)

Collecting dissect.sql<4.0.dev,>=3.0.dev (from dissect.sql[dev]<4.0.dev,>=3.0.dev; extra == "dev"->dissect.target[dev]<4.0.dev,>=3.7.dev)

  Downloading dissect.sql-3.10-py3-none-any.whl.metadata (3.3 kB)

Collecting dissect.squashfs<2.0.dev,>=1.0.dev (from dissect.squashfs[dev]<2.0.dev,>=1.0.dev; extra == "dev"->dissect.target[dev]<4.0.dev,>=3.7.dev)

  Downloading dissect.squashfs-1.7.dev1-py3-none-any.whl.metadata (4.1 kB)

Collecting dissect.thumbcache<2.0.dev,>=1.0.dev (from dissect.thumbcache[dev]<2.0.dev,>=1.0.dev; extra == "dev"->dissect.target[dev]<4.0.dev,>=3.7.dev)

  Downloading dissect.thumbcache-1.9-py3-none-any.whl.metadata (3.4 kB)

Collecting dissect.util<4,>=3 (from dissect.target<4,>=3.7)

  Downloading dissect.util-3.18.dev2-py3-none-any.whl.metadata (3.6 kB)

Collecting dissect.vmfs<4.0.dev,>=3.0.dev (from dissect.vmfs[dev]<4.0.dev,>=3.0.dev; extra == "dev"->dissect.target[dev]<4.0.dev,>=3.7.dev)

  Downloading dissect.vmfs-3.9-py3-none-any.whl.metadata (3.2 kB)

Collecting dissect.volume<4,>=2 (from dissect.target<4,>=3.7)

  Downloading dissect.volume-3.12.dev3-py3-none-any.whl.metadata (3.3 kB)

Collecting dissect.xfs<4.0.dev,>=3.0.dev (from dissect.xfs[dev]<4.0.dev,>=3.0.dev; extra == "dev"->dissect.target[dev]<4.0.dev,>=3.7.dev)

  Downloading dissect.xfs-3.10-py3-none-any.whl.metadata (3.2 kB)

Collecting asn1crypto (from dissect.target[full]<4,>=3.7)

  Downloading asn1crypto-1.5.1-py2.py3-none-any.whl.metadata (13 kB)

Collecting dissect.ole<4,>=3 (from dissect.target[full]<4,>=3.7)

  Downloading dissect.ole-3.9-py3-none-any.whl.metadata (3.3 kB)

Collecting ipython (from dissect.target[full]<4,>=3.7)

  Downloading ipython-8.27.0-py3-none-any.whl.metadata (5.0 kB)

Collecting fusepy (from dissect.target[full]<4,>=3.7)

  Downloading fusepy-3.0.1.tar.gz (11 kB)

  Preparing metadata (setup.py): started

  Preparing metadata (setup.py): finished with status 'done'

Collecting ruamel.yaml (from dissect.target[full]<4,>=3.7)

  Downloading ruamel.yaml-0.18.6-py3-none-any.whl.metadata (23 kB)

Collecting zstandard (from dissect.target[full]<4,>=3.7)

  Downloading zstandard-0.23.0.tar.gz (681 kB)

     ------------------------------------- 681.7/681.7 kB 42.0 MB/s eta 0:00:00

  Installing build dependencies: started

  Installing build dependencies: finished with status 'done'

  Getting requirements to build wheel: started

  Getting requirements to build wheel: finished with status 'done'

  Installing backend dependencies: started

  Installing backend dependencies: finished with status 'done'

  Preparing metadata (pyproject.toml): started

  Preparing metadata (pyproject.toml): finished with status 'done'

Requirement already satisfied: tomli in d:\a\acquire\acquire\.tox\pypy3.10\lib\site-packages (from dissect.target[full]<4,>=3.7) (2.0.1)

Collecting msgpack>=0.5.2 (from flow.record~=3.15.0->dissect.target<4,>=3.7)

  Downloading msgpack-1.0.8.tar.gz (167 kB)

     -------------------------------------- 167.0/167.0 kB 9.8 MB/s eta 0:00:00

  Installing build dependencies: started

  Installing build dependencies: finished with status 'done'

  Getting requirements to build wheel: started

  Getting requirements to build wheel: finished with status 'done'

  Preparing metadata (pyproject.toml): started

  Preparing metadata (pyproject.toml): finished with status 'done'

Collecting tzdata (from flow.record~=3.15.0->dissect.target<4,>=3.7)

  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)

Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich)

  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)

Collecting argon2-cffi-bindings (from argon2-cffi->minio)

  Downloading argon2-cffi-bindings-21.2.0.tar.gz (1.8 MB)

     ---------------------------------------- 1.8/1.8 MB 28.5 MB/s eta 0:00:00

  Installing build dependencies: started

  Installing build dependencies: finished with status 'done'

  Getting requirements to build wheel: started

  Getting requirements to build wheel: finished with status 'done'

  Preparing metadata (pyproject.toml): started

  Preparing metadata (pyproject.toml): finished with status 'error'

pypy3.10: exit 1 (44.28 seconds) D:\a\acquire\acquire> python -I -m pip install dissect.cstruct<5,>=4 dissect.cstruct<5.0.dev,>=4.0.dev dissect.target<4,>=3.7 dissect.target[dev]<4.0.dev,>=3.7.dev dissect.target[full]<4,>=3.7 minio pycryptodome requests requests_toolbelt rich pid=1712
.pkg: _exit> python C:\hostedtoolcache\windows\PyPy\3.10.14\x86\lib\site-packages\pyproject_api\_backend.py True setuptools.build_meta
  pypy3.10: FAIL code 1 (83.16 seconds)
  evaluation failed :( (87.62 seconds)
```
</details>

**Comment by RamonAlvesPS** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by mattip** [comment]
I updated PyPy's built-in version of cffi to latest HEAD. This should be available in the next release. Thanks for pointing it out.

**Comment by jameshilliard** [comment]
I think this needs to be back-ported as well to older branches right? There's a number of older pypy versions supported on [cibuildwheel](https://github.com/pypa/cibuildwheel) that I think will need an updated cffi to build extensions properly.

**Comment by mattip** [comment]
Even if I would backport the changes, we are no longer releasing older PyPy versions.

**Comment by mattip** [comment]
Closing, thanks for the report.
