### ISSUE TITLE
Segmentation Fault with PyPy JIT (threshold=1) in Recursive Function

### ISSUE THREAD

**Issue by zzl261004** [pypy/pypy#5030]
I hope this message finds you well. I have encountered a segmentation fault when running a Python program using PyPy with JIT enabled (threshold=1). When running the script with JIT disabled (--jit off), it raises a RecursionError as expected.

program.py
```python
def rec_fn(x):
    try:
        return rec_fn(x)
    except:
        print(x)

class Obj:
    def __str__(self):
        return str(self)

lst = [1]
for _ in range(10): 
    lst = [lst]
rec_fn(lst)  

obj = Obj()
rec_fn(obj)
```

Running the program with "pypy --jit threshold=1 program.py":
```
[[[[[[[[[[[1]]]]]]]]]]]
Segmentation fault (core dumped)
```

Running the program with "pypy --jit off program.py"
```
[[[[[[[[[[[1]]]]]]]]]]]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nowtest/tmp/program.py", line 3, in rec_fn
    return rec_fn(x)
           ^^^^^^^^^
  File "/nowtest/tmp/program.py", line 5, in rec_fn
    print(x)
  File "/nowtest/tmp/program.py", line 9, in __str__
    return str(self)
           ^^^^^^^^^
  File "/nowtest/tmp/program.py", line 9, in __str__
    return str(self)
           ^^^^^^^^^
  File "/nowtest/tmp/program.py", line 9, in __str__
    return str(self)
           ^^^^^^^^^
  [Previous line repeated 812 more times]
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nowtest/tmp/program.py", line 17, in <module>
    rec_fn(obj)
  File "/nowtest/tmp/program.py", line 5, in rec_fn
    print(x)
  File "/nowtest/tmp/program.py", line 9, in __str__
    return str(self)
           ^^^^^^^^^
  File "/nowtest/tmp/program.py", line 9, in __str__
    return str(self)
           ^^^^^^^^^
  File "/nowtest/tmp/program.py", line 9, in __str__
    return str(self)
           ^^^^^^^^^
  [Previous line repeated 813 more times]
RecursionError: maximum recursion depth exceeded
```

Environment:
Python 3.10.14 (39dc8d3c85a7, Aug 27 2024, 14:32:27)
[PyPy 7.3.17 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Operating System: Ubuntu 22.04.4 LTS

**Comment by cfbolz** [comment]
this is very likely a duplicate of #5021. can you try to reproduce this with a [nightly build](https://buildbot.pypy.org/nightly/py3.10/)? and you could also test to see whether #5021 is fixed and close it, if yes. thanks!

**Comment by zzl261004** [comment]
Thanks. I think this is not a duplicate of #5021. Because I used the command "pypy-c-jit-185276-f6578a9a88dc-linux64/bin/pypy --jit threshold=1 program.py" to execute the program, and it still causes PyPy to encounter a Segmentation fault (core dumped).

This is the nightly build version I used :
```
Python 3.10.14 (f6578a9a88dc, Sep 09 2024, 23:30:46)
[PyPy 7.3.18-alpha0 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
```

**Comment by StanFromIreland** [comment]
I can't reproduce this with a build of py3.11.

**Comment by cfbolz** [comment]
yep, closing, please open if the issue reappears.
