### ISSUE TITLE
PyPy 3 throws an error when attempting to reverse a list, where Python does not.

### ISSUE THREAD

**Issue by TechPro424** [pypy/pypy#5031]
I just installed PyPy (latest available version), and wanted to test it out to see if it works.
I ran the following code with PyPy, it gave the correct output but then threw an error, which was not thrown with CPython 3.11.5
Code:
```py
L2=[10,20,30, 40, 50]
L2.reverse()
print(L2)
```
Error:
```
[50, 40, 30, 20, 10]
Exception in thread Adapter message handler:
Traceback (most recent call last):
  File "C:\Users\TechPro424\scoop\apps\pypy3\current\Lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\TechPro424\scoop\apps\pypy3\current\Lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\TechPro424\scoop\persist\vscodium\data\extensions\ms-python.debugpy-2024.11.0-dev-win32-x64\bundled\libs\debugpy\launcher/../..\debugpy\common\messaging.py", line 1427, in _run_handlers
    self._parser_thread.join()
  File "C:\Users\TechPro424\scoop\apps\pypy3\current\Lib\threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "C:\Users\TechPro424\scoop\apps\pypy3\current\Lib\threading.py", line 1117, in _wait_for_tstate_lock
    lock.release()
RuntimeError: cannot release un-acquired lock
```

**Comment by mattip** [comment]
You are running under some kind of debugger that does not support PyPy, apparently when using scoop? Try running without the debugger.

**Comment by cfbolz** [comment]
It seems to be a known issue, in debugpy maybe? https://github.com/microsoft/debugpy/issues/1198 says it's fixed now though. Do you have recent versions of debugpy and the extension? If this problem reliably occurs for you, maybe you could provide some details how it happens to the debugpy people and help them reproduce.

**Comment by TechPro424** [comment]
Done https://github.com/microsoft/debugpy/issues/1198#issuecomment-2360434909

**Comment by TechPro424** [comment]
https://github.com/microsoft/debugpy/issues/1198#issuecomment-2368779674 seems to be an issue in pypy

**Comment by StanFromIreland** [comment]
Was this fixed in https://github.com/pypy/pypy/commit/93e561bee48bf92a94f145e9b19eea32223fe7a8 ?

**Comment by mattip** [comment]
I think it was closed upstream. I will close it here, please reopen or open a new issue if the problem is seen again.
