### ISSUE TITLE
Suggestions not always appearing

### ISSUE THREAD

**Issue by mattip** [pypy/pypy#5083]
On PyPy3.10, `exec "a=10"` does not print a suggestion
```
>>>> exec "a=10"
  File "<python-input-5>", line 1
    exec "a=10"
    ^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'exec'
```

It does however when the content is not a string
```
>>>> exec f(10)
  File "<python-input-6>", line 1
    exec f(10)
    ^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'exec'. Did you mean exec(...)?
```

**Comment by mattip** [comment]
Here is another place suggestions are no longer appearing, according to the fixes maked to lib-python/3/test/test_code_module:425 they once did appear
```
>>>> try: ham
.... except: eggs
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    try: ham
         ^^^
NameError: name 'ham' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<python-input-0>", line 2, in <module>
    except: eggs
            ^^^^
NameError: name 'eggs' is not defined

```

**Comment by mattip** [comment]
The original problem is fixed, suggestions appear. Closing.
