### ISSUE TITLE
`SystemError` with `gc.dump_rpy_heap`

### ISSUE THREAD

**Issue by devdanzin** [pypy/pypy#5118]
Calling `gc.dump_rpy_heap` with invalid arguments results in a `SystemError`.

Something else also seems to be happening regarding handling of the `file` parameter: when passed a large negative value, some sort of dump into stdout happens, but it looks different from a normal dump to me (and seems to vary between PyPy runs).

```python
Python 3.10.14 (39dc8d3c85a7, Aug 27 2024, 14:32:27)
[PyPy 7.3.17 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import gc
>>>> gc.dump_rpy_heap(-1)
RPython traceback:
  File "pypy_interpreter.c", line 51609, in BuiltinCode1_fastcall_1
  File "rpython_memory_gc.c", line 23123, in dump_rpy_heap
  File "rpython_memory_gc.c", line 23622, in BaseWalker_add_roots
  File "rpython_memory_gc.c", line 23722, in BaseWalker_walk
  File "rpython_memory_gc.c", line 24344, in HeapDumper_writeobj
  File "rpython_memory_gc.c", line 25720, in trace__gc_callback__writeref
  File "rpython_memory_gc.c", line 23867, in HeapDumper_flush
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    gc.dump_rpy_heap(-1)
SystemError: unexpected internal exception (please report a bug): <OSError object at 0x7f523c9796c0>; internal traceback was dumped to stderr
>>>> gc.dump_rpy_heap(-2**35)
# Some memory dump, not sure why it's visible nor where this memory is coming from.
```

Found using fusil by @vstinner.

**Comment by mattip** [comment]
Weird. gc.dump_rpy_heap goes to `app_referencts.dumpy_rpy_heap` which calls interplevel `gc._dump_rpy_heap` which is in [referents.py](https://github.com/pypy/pypy/blob/6360faa8804905f3715b87ec08b27683ed29ff8c/pypy/module/gc/referents.py#L158) and has a `try: except OSError`. So how is the llevel [`rgc.dump_rpy_heap`](https://github.com/pypy/pypy/blob/6360faa8804905f3715b87ec08b27683ed29ff8c/rpython/rlib/rgc.py#L857) not raising properly? It is annotated as [having a `hop.exception_is_here()`]()https://github.com/pypy/pypy/blob/6360faa8804905f3715b87ec08b27683ed29ff8c/rpython/rlib/rgc.py#L1106-L1113.
