### ISSUE TITLE
`SystemError` from `logging._str_formatter.vformat` with invalid `format_string`

### ISSUE THREAD

**Issue by devdanzin** [pypy/pypy#5121]
Calling `logging._str_formatter.vformat` with a `format_string` of `b"\xff"` will result in a `SystemError`:

```python
Python 3.10.14 (39dc8d3c85a7, Aug 27 2024, 14:32:27)
[PyPy 7.3.17 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import logging
>>>> logging._str_formatter.vformat(b"\xff", (), "")
RPython traceback:
  File "pypy_interpreter.c", line 51609, in BuiltinCode1_fastcall_1
  File "pypy_objspace_std_8.c", line 41106, in TemplateFormatter_formatter_parser
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    logging._str_formatter.vformat(b"\xff", (), "")
  File "/home/ubuntu/projects/pypy3.10-v7.3.17-linux64/lib/pypy3.10/string.py", line 165, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/pypy3.10-v7.3.17-linux64/lib/pypy3.10/string.py", line 175, in _vformat
    self.parse(format_string):
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/pypy3.10-v7.3.17-linux64/lib/pypy3.10/string.py", line 259, in parse
    return _string.formatter_parser(format_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: unexpected internal exception (please report a bug): <CheckError object at 0x7f8ef99d7710>; internal traceback was dumped to stderr
```

Found using fusil by @vstinner.

**Comment by cfbolz** [comment]
this is a duplicate of one of your earlier bugs, which affected quite a few functions. it's fixed in a nightly. could you please update the binary you use for fuzzing so that we don't get lots of repeated instances of this problem?

**Comment by devdanzin** [comment]
> this is a duplicate of one of your earlier bugs

Sorry for the noise, will update the binary!
