### ISSUE TITLE
SSLSocket raises SSLEOFError followed by a successful read on the same socket

### ISSUE THREAD

**Issue by ShaneHarvey** [pypy/pypy#5131]
I've encountered a strange issue which appears to only affect pypy3.10, not pypy3.9 or any CPython build. With pypy3.10, pymongo's test suite is encountering spurious connection closures on SSLSockets that are set to non-blocking mode (via `conn.settimeout(0.0)`). I can consistently reproduce the error but I haven't been able to isolate a simple reproduction script yet.

Specifically, SSLSocket.recv_into will 0 bytes which tells the caller that the connection was closed. However, neither the server (running on localhost) nor the client was actually closing the connection. So I added `suppress_ragged_eofs=False` to wrap_socket() and found that in these cases the `lib.SSL_read()` call was actually returning `[SSL: UNEXPECTED_EOF_WHILE_READING] unexpected eof while reading` which later gets translated to SSLEOFError. Now here's the strange part, when I add code to explicitly ignore SSLEOFError and retry the failed read, the next call succeeds(!) and the socket remains useable:

```python
        while total_read < length:
            try:
                read = conn.recv_into(mv[total_read:])
                if conn.DEBUG:
                    print(f"conn.recv_into {conn.fileno()=} {read=}, {total_read=} {length=}")
                if read == 0:
                    raise OSError("connection closed")
                total_read += read
            except SSLEOFError as exc:
                if conn.DEBUG:
                    print(f'conn.recv_into failed with: {exc}, retrying')
                    await asyncio.sleep(1)
                    continue
                raise
            ...
```

Here's an example of the logs when the issue occurs:
```
lib.SSL_read count=-1, err.ssl=1, timeout=0.0, sock=<ssl.SSLSocket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 59632), raddr=('127.0.0.1', 27017)>
lib.SSL_read raising [SSL: UNEXPECTED_EOF_WHILE_READING] unexpected eof while reading
conn.recv_into failed with: [SSL: UNEXPECTED_EOF_WHILE_READING] unexpected eof while reading, retrying
lib.SSL_read count=16, err.ssl=0, timeout=0.0, sock=<ssl.SSLSocket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 59632), raddr=('127.0.0.1', 27017)>
conn.recv_into conn.fileno()=10 read=16, total_read=0 length=16
```

More info:
```
$ python --version
Python 3.10.12 (af44d0b8114cb82c40a07bb9ee9c1ca8a1b3688c, Jun 25 2023, 12:34:44)
[PyPy 7.3.12 with GCC Apple LLVM 14.0.3 (clang-1403.0.22.14.1)]
$ python -c 'import ssl;print(ssl.OPENSSL_VERSION)'
OpenSSL 3.1.1 30 May 2023
```

Again this only happens on pypy 3.10, not pypy 3.9 even though both use the same version of OpenSSL. Do you have any ideas on how this issue could occur?

**Comment by mattip** [comment]
What do the logs look like when using CPython? Maybe some information can be gleaned from comparing the OpenSSL calls. 

The OpenSSL wrapper is written using CFFI, and much of it is pure-python which can be found in `lib/pypy3.10/_cffi_ssl/_stdssl`, (lib/pypy3.9/_cffi_ssl/_stdssl` on 3.9) mostly in the `__init__.py` file in that directory. You can easily play with adding debug info to the code there.

Many things changed between the two python versions.

**Comment by mattip** [comment]
Could you try with the latest nightly build or at least the latest release PyPY 7.3.14? There were some fixes since PyPy 7.3.12.

**Comment by ShaneHarvey** [comment]
I see the same behavior on a nightly build I downloaded last week:
```
$ python --version                                     
Python 3.11.9 (5a2626392f3d, Nov 16 2024, 02:36:04)
[PyPy 7.3.18-alpha0 with GCC Apple LLVM 15.0.0 (clang-1500.3.9.4)]
$ python -c 'import ssl;print(ssl.OPENSSL_VERSION)'                          
OpenSSL 3.3.1 4 Jun 2024
$ pytest -sv -x -- test/asynchronous/test_monitoring.py
...
conn.recv_into failed with: [SSL: UNEXPECTED_EOF_WHILE_READING] unexpected eof while reading, retrying
conn.recv_into conn.fileno()=10 read=16, total_read=0 length=16
```

The only difference with CPython (and pypy 3.9) is that SSL_read doesn't return an EOF. Not very helpful I know.

**Comment by ShaneHarvey** [comment]
I finally got to writing a reproducer script for this bug. Here it is:
```python
```

**Comment by ShaneHarvey** [comment]
I finally got to writing a reproducer script for this bug. Here it is:
```python
import ssl
import socket
import sys
import threading
import time

SERVER_ADDR = ("127.0.0.1", 37017)
CA_FILE = "test/certificates/ca.pem"
SERVER_CERT = "test/certificates/server.pem"
CLIENT_CERT = "test/certificates/client.pem"


def run_server():
    context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH, cafile=CA_FILE)
    context.load_cert_chain(SERVER_CERT)
    context.check_hostname = False
    context.verify_mode = ssl.CERT_NONE
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    server = context.wrap_socket(server, server_side=True)
    server.bind(SERVER_ADDR)
    server.listen(0)

    while True:
        connection, client_address = server.accept()
        t = threading.Thread(target=handle_server_connection, args=(connection, client_address), daemon=True)
        t.start()


def handle_server_connection(connection, client_address):
    client_address = f"{client_address[0]}:{client_address[1]}"
    print(f"server opened connection from {client_address}")
    while True:
        data = connection.recv(1024)
        if not data:
            print(f"server closed connection from {client_address}")
            return
        print(f"server got data from {client_address}: {data}")
        if data == b"CLOSE":
            print(f"server closing {client_address}")
            connection.close()
            return
        # Echo back
        connection.sendall(data)


def get_client():
    context = ssl.create_default_context(cafile=CA_FILE)
    context.load_cert_chain(CLIENT_CERT)
    context.check_hostname = False
    context.verify_mode = ssl.CERT_NONE
    print(f"client connecting")
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.connect(SERVER_ADDR)
    sock = context.wrap_socket(sock)
    return sock


def recv(sock, n):
    timeout = sock.gettimeout()
    sock.settimeout(0)
    mv = memoryview(bytearray(n))
    i = 0
    try:
        while i < n:
            try:
                recv_len = sock.recv_into(mv[i:])
                if recv_len == 0:
                    raise OSError("connection closed")
                i += recv_len
            except (BlockingIOError, ssl.SSLWantReadError, ssl.SSLWantWriteError):
                time.sleep(.0001)
    finally:
        sock.settimeout(timeout)
    return mv.tobytes()


def main():
    print(f"{sys.version=}\n{ssl.OPENSSL_VERSION=}")
    server = threading.Thread(target=run_server, daemon=True)
    server.start()
    time.sleep(1)
    client1 = get_client()
    client2 = get_client()

    client1.send(b"CLIENT A")
    assert recv(client1, 8) == b"CLIENT A"
    client2.send(b"CLIENT B")
    assert recv(client2, 8) == b"CLIENT B"
    time.sleep(1)
    client1.send(b"CLOSE")
    assert client1.recv(10) == b""

    client2.send(b"CLIENT B")

    # client2 should still be open even if the server closed client1.
    # On PyPy this line fails with "OSError: connection closed".
    # On CPython this line succeeds as expected.
    assert recv(client2, 8) == b"CLIENT B"


if __name__ == "__main__":
    main()
```

Here's the correct output on CPython:
```
$ python repro-pypy-ssl-bug.py
sys.version='3.13.0 (v3.13.0:60403a5409f, Oct  7 2024, 00:37:40) [Clang 15.0.0 (clang-1500.3.9.4)]'
ssl.OPENSSL_VERSION='OpenSSL 3.0.15 3 Sep 2024'
client connecting
server opened connection from 127.0.0.1:62296
client connecting
server got data from 127.0.0.1:62296: b'CLIENT A'
server opened connection from 127.0.0.1:62297
server got data from 127.0.0.1:62297: b'CLIENT B'
server got data from 127.0.0.1:62296: b'CLOSE'
server closing 127.0.0.1:62296
server got data from 127.0.0.1:62297: b'CLIENT B'
```

Here's the buggy output on PyPy:
```
$  pypy3 repro-pypy-ssl-bug.py 
sys.version='3.10.12 (af44d0b8114cb82c40a07bb9ee9c1ca8a1b3688c, Jun 25 2023, 12:34:44)\n[PyPy 7.3.12 with GCC Apple LLVM 14.0.3 (clang-1403.0.22.14.1)]'
ssl.OPENSSL_VERSION='OpenSSL 3.1.1 30 May 2023'
client connecting
server opened connection from 127.0.0.1:62301
client connecting
server got data from 127.0.0.1:62301: b'CLIENT A'
server opened connection from 127.0.0.1:62302
server got data from 127.0.0.1:62302: b'CLIENT B'
server got data from 127.0.0.1:62301: b'CLOSE'
server closing 127.0.0.1:62301
server got data from 127.0.0.1:62302: b'CLIENT B'
Traceback (most recent call last):
  File "/Users/shane/git/mongo-python-driver/repro-pypy-ssl-bug.py", line 104, in <module>
    main()
  File "/Users/shane/git/mongo-python-driver/repro-pypy-ssl-bug.py", line 100, in main
    assert recv(client2, 8) == b"CLIENT B"
           ^^^^^^^^^^^^^^^^
  File "/Users/shane/git/mongo-python-driver/repro-pypy-ssl-bug.py", line 70, in recv
    raise OSError("connection closed")
OSError: connection closed
```

To run the script you'll need to supply the ca/client/server certificates. I'm used the ones from pymongo's test suite here: https://github.com/mongodb/mongo-python-driver/tree/master/test/certificates

PS. Github's new UI caused me to stumble into closing this issue by mistake and I don't have permission to reopen it. Could you open it?
